# 🟡LEVEL 1: Must-Know Basics

- Load deliveries.csv into a DataFrame.

- Print the first 5 rows and last 5 rows.

- Check the shape of the dataset.

- Check column names.

- Get summary statistics using .describe().

- Check data types and null counts using .info().

### Loading Data

In [201]:
import pandas as pd
deliveries=pd.read_csv("deliveries.csv")
matches=pd.read_csv("matches.csv")

In [202]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [203]:
deliveries.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [204]:
deliveries.shape

(260920, 17)

In [205]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [206]:
deliveries.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [207]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

 #### 🎯 PROFESSIONAL RATING
#### ⭐ 9 / 10

Why not 10?

Minor duplication

Slightly extra file loaded before it’s needed

Conceptually: STRONG

---

---

---


# 🟡 LEVEL 2: Selection & Filtering

- Select the "batter" column and print the first 10 values.

- Select multiple columns: "batter" and "batsman_runs" and print first 10 rows.

- Filter all rows where batsman_runs == 6.

- Filter all rows where batting_team == "Mumbai Indians" and batsman_runs == 6.

- Use .iloc[] to print first 5 rows and first 3 columns.

- Use .loc[] to print rows 10 to 20 and columns "batter" and "batsman_runs".

In [208]:
deliveries["batter"].head(10)

0     SC Ganguly
1    BB McCullum
2    BB McCullum
3    BB McCullum
4    BB McCullum
5    BB McCullum
6    BB McCullum
7    BB McCullum
8    BB McCullum
9    BB McCullum
Name: batter, dtype: object

In [209]:
deliveries[["batter","batsman_runs"]]

             batter  batsman_runs
0        SC Ganguly             0
1       BB McCullum             0
2       BB McCullum             0
3       BB McCullum             0
4       BB McCullum             0
...             ...           ...
260915      SS Iyer             1
260916      VR Iyer             1
260917      VR Iyer             1
260918      SS Iyer             1
260919      VR Iyer             1

[260920 rows x 2 columns]

In [210]:
deliveries[deliveries["batsman_runs"]==6]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
20,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,BB McCullum,AA Noffke,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
25,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,7,BB McCullum,AA Noffke,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
60,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,9,5,BB McCullum,SB Joshi,RT Ponting,6,0,6,NaN,0,NaN,NaN,NaN
65,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,10,4,RT Ponting,JH Kallis,BB McCullum,6,0,6,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260868,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,2,2,VR Iyer,B Kumar,Rahmanullah Gurbaz,6,0,6,NaN,0,NaN,NaN,NaN
260869,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,2,3,VR Iyer,B Kumar,Rahmanullah Gurbaz,6,0,6,NaN,0,NaN,NaN,NaN
260889,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,3,VR Iyer,T Natarajan,Rahmanullah Gurbaz,6,0,6,NaN,0,NaN,NaN,NaN
260895,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,6,3,Rahmanullah Gurbaz,Shahbaz Ahmed,VR Iyer,6,0,6,NaN,0,NaN,NaN,NaN
260908,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,8,4,Rahmanullah Gurbaz,Shahbaz Ahmed,VR Iyer,6,0,6,NaN,0,NaN,NaN,NaN

In [211]:
deliveries[(deliveries["batting_team"]=="Mumbai Indians")&(deliveries["batsman_runs"]==6)]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
723,335985,1,Mumbai Indians,Royal Challengers Bangalore,4,7,ST Jayasuriya,JH Kallis,RV Uthappa,6,0,6,NaN,0,NaN,NaN,NaN
765,335985,1,Mumbai Indians,Royal Challengers Bangalore,11,6,RV Uthappa,R Vinay Kumar,PR Shah,6,0,6,NaN,0,NaN,NaN,NaN
798,335985,1,Mumbai Indians,Royal Challengers Bangalore,17,2,AM Nayar,R Vinay Kumar,SM Pollock,6,0,6,NaN,0,NaN,NaN,NaN
801,335985,1,Mumbai Indians,Royal Challengers Bangalore,17,5,SM Pollock,R Vinay Kumar,AM Nayar,6,0,6,NaN,0,NaN,NaN,NaN
808,335985,1,Mumbai Indians,Royal Challengers Bangalore,18,6,SM Pollock,P Kumar,Harbhajan Singh,6,0,6,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259513,1426305,2,Mumbai Indians,Lucknow Super Giants,16,6,Naman Dhir,KH Pandya,Ishan Kishan,6,0,6,NaN,0,NaN,NaN,NaN
259524,1426305,2,Mumbai Indians,Lucknow Super Giants,18,3,Naman Dhir,Mohsin Khan,Ishan Kishan,6,0,6,NaN,0,NaN,NaN,NaN
259525,1426305,2,Mumbai Indians,Lucknow Super Giants,18,4,Naman Dhir,Mohsin Khan,Ishan Kishan,6,0,6,NaN,0,NaN,NaN,NaN
259529,1426305,2,Mumbai Indians,Lucknow Super Giants,19,1,Naman Dhir,Naveen-ul-Haq,Ishan Kishan,6,0,6,NaN,0,NaN,NaN,NaN
259535,1426305,2,Mumbai Indians,Lucknow Super Giants,19,7,Naman Dhir,Naveen-ul-Haq,R Shepherd,6,0,6,NaN,0,NaN,NaN,NaN

In [212]:
#Use .iloc[] to print first 5 rows and first 3 columns
deliveries.iloc[0:5,0:3]

   match_id  inning           batting_team
0    335982       1  Kolkata Knight Riders
1    335982       1  Kolkata Knight Riders
2    335982       1  Kolkata Knight Riders
3    335982       1  Kolkata Knight Riders
4    335982       1  Kolkata Knight Riders

In [213]:
#Use .loc[] to print rows 10 to 20 and columns "batter" and "batsman_runs".
deliveries.loc[10:20,["batter","batsman_runs"]]

         batter  batsman_runs
10  BB McCullum             6
11  BB McCullum             4
12  BB McCullum             0
13   SC Ganguly             0
14   SC Ganguly             0
15   SC Ganguly             0
16  BB McCullum             4
17  BB McCullum             1
18   SC Ganguly             0
19  BB McCullum             0
20  BB McCullum             6

#### 🎯 PROFESSIONAL RATING
#### ⭐ 8.5 / 10
Breakdown:

Concepts: Excellent

Syntax understanding: Strong

One column-name mistake: −1.5

---

---

---

# 🟡LEVEL 3: Grouping & Aggregation

- Calculate total runs scored by each batter.

- Calculate total balls faced by each batter.

- Calculate total runs scored by each team.

- Calculate strike rate for each batter (total_runs / balls_faced * 100).

- Use .agg() to get both total runs and total balls faced per batter in one line.

- Use .reset_index() after your groupby to convert index to column.

- Find top 5 batters by total runs.

- Find top 5 batters by strike rate, but only include those who faced ≥ 100 balls.

In [214]:
deliveries.groupby('batter')["batsman_runs"].sum().sort_values(ascending=False).reset_index()

           batter  batsman_runs
0         V Kohli          8014
1        S Dhawan          6769
2       RG Sharma          6630
3       DA Warner          6567
4        SK Raina          5536
..            ...           ...
668       S Ladda             0
669  S Lamichhane             0
670  Abdur Razzak             0
671   SS Cottrell             0
672       KM Asif             0

[673 rows x 2 columns]

In [215]:
deliveries.groupby('batter').size().sort_values(ascending=False).reset_index().rename(columns={0:"total_balls_faced"})

            batter  total_balls_faced
0          V Kohli               6236
1         S Dhawan               5483
2        RG Sharma               5183
3        DA Warner               4849
4         SK Raina               4177
..             ...                ...
668     YA Abdulla                  1
669  DP Vijaykumar                  1
670  Y Prithvi Raj                  1
671      S Kaushik                  1
672  NJ Rimmington                  1

[673 rows x 2 columns]

In [216]:
deliveries.groupby('batting_team')["batsman_runs"].sum().sort_values(ascending=False).reset_index().head(10).rename(columns={"batsman_runs":"total_runs"})

                  batting_team  total_runs
0               Mumbai Indians       39946
1        Kolkata Knight Riders       37149
2          Chennai Super Kings       36739
3  Royal Challengers Bangalore       35810
4             Rajasthan Royals       33074
5              Kings XI Punjab       28541
6          Sunrisers Hyderabad       27641
7             Delhi Daredevils       23022
8               Delhi Capitals       14229
9              Deccan Chargers       10885

In [217]:
#Calculate strike rate for each batter (total_runs / balls_faced * 100).
total_runs=deliveries.groupby('batter')["batsman_runs"].sum()
balls_faced=deliveries.groupby('batter').size()
(total_runs / balls_faced * 100).sort_values(ascending=False).reset_index().rename(columns={0:"strike_rate"})

              batter  strike_rate
0             L Wood   300.000000
1         B Stanlake   250.000000
2    J Fraser-McGurk   220.000000
3      R Sai Kishore   216.666667
4           Umar Gul   205.263158
..               ...          ...
668         JL Denly     0.000000
669      Sunny Gupta     0.000000
670           U Kaul     0.000000
671          C Nanda     0.000000
672        IC Pandey     0.000000

[673 rows x 2 columns]

In [218]:
deliveries.groupby("batter").agg(
    total_runs=('batsman_runs','sum'),
    total_balls=('batsman_runs','size')
).reset_index()

             batter  total_runs  total_balls
0    A Ashish Reddy         280          196
1          A Badoni         634          505
2        A Chandila           4            7
3          A Chopra          53           75
4       A Choudhary          25           20
..              ...         ...          ...
668   Yashpal Singh          47           67
669     Younis Khan           3            7
670   Yudhvir Singh          22           16
671    Yuvraj Singh        2754         2207
672          Z Khan         117          141

[673 rows x 3 columns]

In [219]:
#Calculate strike rate for each batter (total_runs / balls_faced * 100) with  filter batters with ≥ 500 balls
total_runs=deliveries.groupby('batter')["batsman_runs"].sum()

balls_faced=deliveries.groupby('batter').size()

strike_rate=(total_runs / balls_faced * 100)
#strike_rate
fair_strike_rate=strike_rate[balls_faced>500].sort_values(ascending=False).reset_index()
fair_strike_rate.head()

           batter           0
0      AD Russell  164.224422
1       H Klaasen  161.990212
2       SP Narine  155.894309
3        N Pooran  154.768154
4  LS Livingstone  154.187192

##### 🟡 Level 3: Grouping & Aggregation (CORE)

#### Status: ✅ COMPLETED WELL
##### Score: 8.5 / 10

##### This is where many learners quit — you didn’t.

You now understand:

-  `groupby` logic (keys → index)

-` .sum(), .size(), .count() `

- `.agg()` for multiple metrics

- `reset_index()` and why it matters

- strike rate logic (runs / balls × 100)

- fairness filtering `(balls >= X)`

- `index alignment` (this is BIG 🔥)

  ---

  ---

  ---

#  🟡Level 4 SORTING & RANKING (Medium)

#### 🔑 Functions you will master in Level 4

#### We will use only these (nothing extra):

- **.sort_values()**

- **.head()**

- **.tail()**

- **.nlargest()**

- **.nsmallest()**

### 🔹 1. .sort_values() (THE CORE)
#### Syntax:

In [291]:
#df.sort_values(by="column", ascending=False)

In [ ]:
runs_per_batter = deliveries.groupby("batter")["batsman_runs"].sum().reset_index()

runs_per_batter.sort_values("batsman_runs",ascending=False)

In [ ]:
runs_per_batter = deliveries.groupby("batter")["batsman_runs"].sum().reset_index()

runs_per_batter.nlargest(10,"batsman_runs")

#### 🔹 3. .nlargest() (shortcut professionals love)
##### Instead of:

In [ ]:
.sort_values("batsman_runs", ascending=False).head(10)

#### You can write:

In [ ]:
runs_per_batter.nlargest(10, "batsman_runs")

In [ ]:
deliveries.groupby("batter")["batsman_runs"].sum().sort_values(ascending=False).reset_index()

In [ ]:
deliveries.groupby("batter")["batsman_runs"].sum().nlargest(10).reset_index()

# Exersise

#### 📝 Task 1: Top Run Scorers

#### Question:
 Top 10 batters by total runs in IPL.

👉 Hint:
groupby → sum → sort

In [ ]:
total_runs=deliveries.groupby("batter")["batsman_runs"].sum().nlargest(10).reset_index()
total_runs

#### 📝 Task 2: Bottom Run Scorers

#### Question:
- Bottom 10 batters by total runs
(minimum: faced at least 500 balls)

👉 Hint:
Use the balls filter first, then sort.

In [ ]:
runs=deliveries.groupby("batter")["batsman_runs"].sum()
balls=deliveries.groupby("batter").size()


bottom_run_scorers=runs[balls>=500]
bottom_run_scorers.sort_values(ascending=True).head(10).reset_index()

#### 📝 Task 3: Best Strike Rate (Fair)

#### Question:
- Top 10 batters by strike rate
(only batters who faced ≥ 500 balls)

👉 Hint:

you already know this logic

just add ranking

In [ ]:
runs=deliveries.groupby("batter")["batsman_runs"].sum()
balls=deliveries.groupby("batter").size()

strike_rate=(runs/balls)*100
fair_strike_rate=strike_rate[balls>=500]
fair_strike_rate.nlargest(10).reset_index()

#### 📝 Task 4: Worst Strike Rate (Consistent)

#### Question:
- Worst 10 strike rates
(≥ 500 balls)

👉 Hint:

ascending sort

think like an analyst, not a fan 😉

In [ ]:
runs=deliveries.groupby("batter")["batsman_runs"].sum()
balls=deliveries.groupby("batter").size()

strike_rate=(runs/balls)*100
wrost_strike_rate=strike_rate[balls>=500]
wrost_strike_rate.sort_values(ascending=True).head(10).reset_index()

#### 🟡 Level 4: Sorting & Ranking

#### Status: ✅ CONFIDENT
#### Score: 8.5 / 10

### You can:

- rank top & bottom performers

- use `.sort_values()` , `.nlargest()`

- explain why ranking without filters is misleading

- create portfolio-ready insights

#### Your logic here is analyst-grade, not tutorial-grade.

---

---

---

# 🛠 Level 5 Functions (We’ll master all)
- 1️⃣ `.isnull() /` `.notnull()`
- 2️⃣ `.sum()` (with isnull)
- 3️⃣ `.dropna()`
- 4️⃣ `.fillna()`
- 5️⃣ `.duplicated()`
- 6️⃣ `.drop_duplicates()`
- 7️⃣ `.astype()`

In [ ]:
deliveries.isnull().sum()

In [ ]:
deliveries.notnull().sum()

In [ ]:
(deliveries.isnull().sum()/len(deliveries))*100

In [ ]:
# It drop all the  NAN values in the dataset
df=deliveries.dropna()

In [ ]:
(df.isnull().sum()/len(df))*100

In [ ]:
# Only removes rows where dismissal_kind info is missing (if analysis requires it).
df=deliveries.dropna(subset=["dismissal_kind"])

In [ ]:
(df.isnull().sum()/len(df))*100

In [ ]:
#deliveries["extras_type"]=deliveries["extras_type"].fillna("NO Extra").reset_index()
deliveries["extras_type"]=deliveries["extras_type"].fillna("No Extra")

In [ ]:
deliveries

In [ ]:
deliveries.duplicated().sum()

In [ ]:
deliveries.drop_duplicates()

In [ ]:
deliveries.dtypes

In [ ]:
deliveries["ball"]=deliveries["ball"].astype(int)

In [ ]:
deliveries["over"]=deliveries["over"].astype(int)

In [ ]:
deliveries.dtypes

# 🧪 EXERCISES

#### 📝 Task 1: Missing Values

Find how many missing values are in each column.

Identify 2 columns where missing values are normal, not errors.

Explain why they are normal.

In [ ]:
# Q 1:
deliveries.isnull().sum().reset_index()

In [ ]:
deliveries.head(20)

In [ ]:
# Q2 :Identify 2 columns where missing values are normal, not errors.

#Explain why they are normal.
i believe these are extra type,player dismissed

#### 📝 Task 2: Smart Filling

Fill missing extras_type with "No Extra".

Verify that no NaNs remain in that column.

In [ ]:
deliveries["extras_type"]=deliveries["extras_type"].fillna("NO Extra")

In [ ]:
deliveries.head(20)

#### 📝 Task 3: Duplicate Check

Check if deliveries has duplicate rows.

If yes, remove them.

Print dataset shape before and after.

In [ ]:
# task 3 correct way to solve it 
before = deliveries.shape
deliveries = deliveries.drop_duplicates()
after = deliveries.shape

print(before, after)

In [ ]:
deliveries.duplicated().sum()

In [ ]:
# As dataset (deliveries) does not contains any duplicatevalue but the ethod to remove duplicate values is given below
deliveries.drop_duplicates()

#### 📝 Task 4: Data Types

Check data types of all columns.

Convert over and ball to integer (if not already).

Explain why numeric type matters for analysis.

deliveries.dtypes

In [ ]:
# Convert over and ball to integer (if not already)

deliveries["over"]=deliveries["over"].astype(int)

In [ ]:
deliveries["ball"]=deliveries["ball"].astype(int)

In [ ]:
# Explain why numeric type matters for analysis. 
Beucase we can mostly do analytical work using Numbers not text  becuase with the help of numbers it is every time solve to find patterns and solve any problem even if require to do prediction about future which is not accrate if we use only text

#### 🏆 FINAL LEVEL-5 SCORE
#### ⭐ 8.8 / 10 — PASS (STRONG JUNIOR ANALYST LEVEL)

### You:

- Understand why data is cleaned

- Avoid dangerous blanket operations

- Make meaning-based decisions

- Think beyond syntax

- This is not beginner behavior anymore.

# 🟠 LEVEL 6: STRING & DATE OPERATIONS (Medium–Hard)

#### This level fixes messy text and time-based analysis
#### These skills are used daily by data analysts.

#### 🧠 Why Level 6 Matters (Very Important)

#### Real datasets have problems like:

- Player names with extra spaces

- Inconsistent casing (V Kohli, v kohli, VIRAT KOHLI)

- Seasons stored as text

- Dates stored as strings

- Need to analyze year-wise / season-wise trends

- Without Level 6 → analysis breaks.

#### 1️⃣ .str.lower() / .str.upper()
#### Problem

Same player appears in different casing.

In [ ]:
deliveries["batter"]=deliveries["batter"].str.upper()
deliveries["batter"].reset_index()

In [ ]:
deliveries["batter"]=deliveries["batter"].str.lower()
deliveries["batter"].reset_index()

#### 2️⃣ .str.strip() (VERY IMPORTANT)
#### Problem

Hidden spaces break filtering:

In [ ]:
deliveries["batter"]=deliveries["batter"].str.strip()
deliveries["batter"].reset_index()

#### 3️⃣ .str.contains() (Powerful Filtering)
#### Question

- Find all rows where batter name contains “kohli”

In [ ]:
deliveries[deliveries["batter"].str.contains("kohli",case=False)]

In [ ]:
deliveries.head(10)

In [ ]:
deliveries["batting_team"] = deliveries["batting_team"].str.replace("Rising Pune Supergiant", "RPS")
# Verifying above Condition
deliveries.groupby("batting_team")["batsman_runs"].sum().head(30).reset_index()

### Note 
##### 🧠 IMPORTANT STRING RULE (WRITE THIS)

- .str works on Series, not DataFrames
##### Always apply .str to a single column

#### PART 2️⃣: DATE & TIME OPERATIONS

#### Dates unlock:

- season analysis

- trends

- growth/decline

- consistency over years

In [ ]:
matches.dtypes

#### 5️⃣ pd.to_datetime()

In [ ]:
# If date is object:
matches["date"]=pd.to_datetime(matches["date"])

#### 6️⃣ Extract Date Parts (.dt)

In [ ]:
matches["year"]=matches["date"].dt.year

matches["month"]=matches["date"].dt.month

matches["day_name"]=matches["date"].dt.day_name()

#### 7️⃣ Season-Wise Analysis (IPL Gold 🔥)

#### Example:

In [ ]:
matches["season"]=matches["date"].dt.year
matches["season"].value_counts().sort_index(ascending=False).reset_index()

### 🧪 LEVEL 6 EXERCISES



#### 📝 Task 1: String Cleaning

1.Convert batter column to lowercase

2.Remove extra spaces (strip)

3.Verify by checking unique values

In [ ]:
deliveries["batter"]=deliveries["batter"].str.lower().str.strip()
deliveries["batter"].head(10).reset_index()

#### 📝 Task 2: String Filtering

1.Filter all rows where batter contains "kohli"

2.Count total balls faced by Kohli

3.Count total runs scored by Kohli

In [ ]:
kohli=deliveries[deliveries["batter"].str.contains("kohli",case=False)]
kohli

In [ ]:
# Count total balls faced by Kohli
kohli.groupby("batter")["ball"].size().sum()

In [ ]:
# Count total runs scored by Kohli
kohli["batsman_runs"].sum()

##### 📝 Task 3: Date Conversion

1. Convert matches["date"] to datetime

2. Extract season from date

3. Show number of matches per season (sorted)

In [ ]:
#
matches["date"]=pd.to_datetime(matches["date"])

In [ ]:
#
matches["year"]=matches["date"].dt.year

matches["month"]=matches["date"].dt.month

matches["day_name"]=matches["date"].dt.day_name()

In [ ]:
matches["season"]=matches["date"].dt.year
matches["season"].sort_index().head(10).reset_index()

##### ⭐ Final Level 6 Rating
##### 🟢 Overall Level 6 Score: 8.5 / 10

### This means:

- You understand the concepts

- You can apply them without copying

- Your mistakes are minor & stylistic, not conceptual

👉 This is exactly where a strong junior data analyst should be.

# 🧠 LEVEL 7 — Combining Datasets (REAL ANALYST SKILL)
#### Why Level 7 matters (very important)

#### In the real world:

- Data is never in one file

- One table has IDs

- Another table has details

You must combine them to answer questions.

📌 In IPL:

`matches` → match-level info (date, season, teams)

`deliveries` → ball-by-ball info (runs, batter)

👉 To answer season-wise player stats, both are required

#### 👉 To answer season-wise player stats, both are required

##### 🔑 Key Concept Before Code (READ THIS CAREFULLY)
##### Common column between datasets:

- This is the bridge.

- “Give me ball-by-ball data + match info”

- That is called a JOIN / MERGE

#### 1️⃣ merge() — The MOST IMPORTANT Function in Pandas
##### Basic syntax (memorize this very important Umair):
##### pd.merge( left_df ,right_df ,on="common_columns" )

In [ ]:
merged = pd.merge(
    deliveries,
    matches,
    left_on="match_id",
    right_on="id"
)

In [ ]:
merged.columns

#### 3️⃣ First Simple Question (Level 7 Starter)
##### ❓ Total runs scored season-wise

In [ ]:
merged.groupby("season")["batsman_runs"].sum()

#### 🔹 TASK 1: Season-wise Runs by Virat Kohli

### Goal:
##### Find how many runs Virat Kohli scored in each IPL season.

### Rules:

- Use both datasets

- Use merge

- Output should be:

- season

- total_runs

📌 Hint:

##### Batter data → deliveries

##### Season data → matches

#### Join key → match_id ↔ id

In [ ]:
merged=pd.merge(deliveries,
               matches,
               left_on="match_id",
               right_on="id")

In [243]:
kohli_records=merged [ merged [ "batter" ] == "V Kohli" ]

kohli_records.groupby( "season" )[ "batsman_runs" ].sum()

season
2007/08    165
2009       246
2009/10    307
2011       557
2012       364
2013       639
2014       359
2015       505
2016       973
2017       308
2018       530
2019       464
2020/21    471
2021       405
2022       341
2023       639
2024       741
Name: batsman_runs, dtype: int64

#### 🔹 TASK 2: Best Season of Virat Kohli

#### Goal:
#### Which season was Virat Kohli’s highest run-scoring IPL season?

#### Rules:

- Use result from Task 1

- Rank seasons

#### Return:

- season

- runs

In [232]:
# Merge deliveries and matches
merged = pd.merge(
    deliveries,
    matches,
    left_on="match_id",
    right_on="id"
)

# Filter Virat Kohli records
kohli_records = merged[merged["batter"] == "V Kohli"]

# Runs per season
kohli_season_runs = kohli_records.groupby("season")["batsman_runs"].sum()

# Best season (season + runs)
kohli_best_season = kohli_season_runs.idxmax()
kohli_best_runs = kohli_season_runs.max()

kohli_best_season, kohli_best_runs

('2016', 973)

#### 🔹 TASK 3: Top 5 Batters by Total Runs (All Seasons Combined)

#### Goal:
#### Find top 5 batters by total IPL runs.

#### Rules:

- Use merged dataset

- Group by batter

- Sort descending

- Reset index

In [245]:
merged.groupby("batter")["batsman_runs"].sum().nlargest(5).reset_index()

      batter  batsman_runs
0    V Kohli          8014
1   S Dhawan          6769
2  RG Sharma          6630
3  DA Warner          6567
4   SK Raina          5536

#### 🔹 TASK 4: Season-wise Total Runs by Team

#### Goal:
##### For each season, calculate total runs scored by each team.

#### Rules:

- Use merged data

- Group by:

- season

- batting_team

- Aggregate runs

In [227]:
merged.groupby(["season","batting_team"])["batsman_runs"].sum().reset_index()

      season                 batting_team  batsman_runs
0    2007/08          Chennai Super Kings          2365
1    2007/08              Deccan Chargers          2117
2    2007/08             Delhi Daredevils          2000
3    2007/08              Kings XI Punjab          2340
4    2007/08        Kolkata Knight Riders          1801
..       ...                          ...           ...
141     2024               Mumbai Indians          2422
142     2024                 Punjab Kings          2372
143     2024             Rajasthan Royals          2533
144     2024  Royal Challengers Bengaluru          2789
145     2024          Sunrisers Hyderabad          2906

[146 rows x 3 columns]

#### 🔹 TASK 5 (Thinking Task – No Code Explanation Required)

##### Answer in 1–2 lines:

##### Why is merge() placed in Level 7 and not earlier levels?

In [228]:
#lets take the exmaple of array every time first we learn basic of c++ then moves to 1D array once it completely understand we jumps to 2D array in short understand basic first then jumping to complex topics is best to learn anything

#### 🧠 One-Line Rule (Remember This Forever)

#### If columns are same → concat
#### If columns are different → merge

#### This rule alone solves 80% of combine-data confusion.

🏏 IPL Context (Real Analyst Thinking)

#### 🧠 FINAL LEVEL-7 EVALUATION
#### Area	Score
#### Merge logic	⭐⭐⭐⭐⭐
#### Groupby usage	⭐⭐⭐⭐
#### Aggregation	⭐⭐⭐⭐
#### Analytical thinking	⭐⭐⭐⭐
#### Over-engineering awareness	⭐⭐⭐
#### 🎯 Overall Level-7 Score: 8/10

# 🔴 LEVEL 8 — ADVANCED ANALYST TOOLS (FINAL STAGE)

You already know what the data is.
Now we learn how to summarize, reshape, and reason with it.

### We’ll master 4 weapons:

- 1️⃣ `value_counts()`
- 2️⃣` pivot_table()`
- 3️⃣ `apply()`
- 4️⃣ set_index() + advanced reset_index()

We start with the easiest + most powerful.

#### **🔥 🔵 FUNCTION 1: ` value_counts()` — The Analyst’s Shortcut**
🧠 What it answers

#### “How often does each value appear?”

This replaces:

groupby + count

multiple lines of code

### 🏏 IPL Example 1 — Most Sixes (Cleaner Way)

In [249]:
deliveries[deliveries["batsman_runs"] == 6]["batter"].value_counts().head(10)

#📌 This answers:

#Who hit the most sixes in IPL history?

#One line. Analyst-approved.

batter
CH Gayle          359
RG Sharma         281
V Kohli           273
AB de Villiers    253
MS Dhoni          252
DA Warner         236
KA Pollard        224
AD Russell        209
SV Samson         206
SK Raina          204
Name: count, dtype: int64

### 🏏 IPL Example 2 — Wicket Types Distribution

In [250]:
deliveries["dismissal_kind"].value_counts()
#📌 Insight:

#Caught dominates

#LBW vs Bowled comparison

#Helps bowling analysis

dismissal_kind
caught                   8063
bowled                   2212
run out                  1114
lbw                       800
caught and bowled         367
stumped                   358
retired hurt               15
hit wicket                 15
obstructing the field       3
retired out                 3
Name: count, dtype: int64

### 🏏 IPL Example 3 — Matches per Season

In [251]:
matches["season"].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
Name: count, dtype: int64

### 🧪 YOUR TASK (Do NOT rush)
### Task A

#### Find Top 5 batters who faced the most balls using value_counts().

👉 Hint:

- Each row = 1 ball

- Column: batter

In [234]:
deliveries["batter"].value_counts().head(5)

batter
V Kohli      6236
S Dhawan     5483
RG Sharma    5183
DA Warner    4849
SK Raina     4177
Name: count, dtype: int64

### Task B

#### Find Top 5 bowlers who took the most wickets.

👉 Hint:

- is_wicket == 1

- Column: bowler

In [260]:
deliveries[deliveries["is_wicket"]==1]["bowler"].value_counts().head(5).reset_index().rename(columns={"count":"total_wickets"})

      bowler  total_wickets
0  YS Chahal            213
1   DJ Bravo            207
2  PP Chawla            201
3  SP Narine            200
4   R Ashwin            198

#### Task C (Thinking Test)

#### Q Why is value_counts() often better than groupby().count()?

#### Ans: because it is a shortcut of  groupby().count() and alot professional data analyst mostly used it

#### 🔥 🔵 FUNCTION 1:  `pivot_table() ` — The Analyst’s love

##### Use pivot_table when you want to compare one metric across two categories.

##### Examples:

`Team vs Season`

`Batter vs Season`

`Team vs Over phase`
#### 🔹 Used — COMPARISON questions

- (this is where pivot_table is born)

“Runs by each team in each season”
“Sixes by each batter per season”

- These cannot be answered properly as a list.

They need a TABLE.

#### Every pivot_table answers this sentence:

- “Show me VALUES,
- grouped by ROWS,
- compared across COLUMNS,
- using THIS calculation.”

##### That’s it. Nothing else.

#### What does pivot_table replace?

##### Without it, your brain would do:

- groupby team + season

- sum runs

- reshape data

- unstack

clean columns

##### Too much thinking ❌

👉 pivot_table does all of this in one step.

##### Use pivot_table when you want to compare one metric across two categories.

#### Examples:

`Team vs Season`

`Batter vs Season`

`Team vs Over phase`

#### ❓ Why is pivot_table better than groupby for “team vs season” analysis?
pivot_table is better than groupby when we want to compare one metric across two categories,
because it automatically arranges the result into rows and columns, making comparisons easier and clearer.
pivot_table is better than groupby when we want to compare one metric across two categories, because it automatically arranges the result into rows and columns, making comparisons easier and clearer.
#### this in an interview → very strong answer.

#### 🧪 FIRST & SIMPLE pivot_table (Very Easy)
#### 🎯 Question:

“Total runs scored by each team”

- This is actually a warm-up pivot.

#### Code:

In [ ]:
pd.pivot_table(
    data=deliveries,
    values="batsman_runs",
    index="batting_team",
    aggfunc="sum"
)

#### 🧠 What happened?

- values → what to calculate (runs)

- index → row category (team)

- aggfunc → how (sum)

##### This output is same as groupby, but cleaner.

#### 🧪 REAL pivot_table (Actual use)
##### 🎯 Question:

`“Total runs by each team in each season”`

In [272]:
pd.pivot_table(
    data=merged,
    index="batting_team",
    columns="season",
    values="batsman_runs",
    aggfunc="sum"
)

season,2007/08,2009,2009/10,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020/21,2021,2022,2023,2024
batting_team,,,,,,,,,,,,,,,,,
Chennai Super Kings,2365.0,2084.0,2442.0,2461.0,2717.0,2671.0,2519.0,2564.0,NaN,NaN,2698.0,2346.0,2095.0,2607.0,2165.0,2600.0,2405.0
Deccan Chargers,2117.0,2283.0,2244.0,2039.0,2202.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2428.0,2658.0,2387.0,2218.0,2073.0,2465.0
Delhi Daredevils,2000.0,2021.0,2028.0,1942.0,2502.0,2114.0,1978.0,2061.0,1995.0,2131.0,2250.0,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2318.0,2311.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2517.0,2906.0,1934.0
Kings XI Punjab,2340.0,1768.0,2165.0,2080.0,2286.0,2312.0,2824.0,1902.0,2051.0,2099.0,2124.0,2326.0,2264.0,NaN,NaN,NaN,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,1758.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,1801.0,1678.0,1978.0,1905.0,2356.0,2134.0,2382.0,1939.0,2133.0,2354.0,2655.0,2359.0,2124.0,2423.0,2109.0,2338.0,2481.0
Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2405.0,2326.0,2350.0
Mumbai Indians,1897.0,1766.0,2553.0,2143.0,2333.0,2845.0,2235.0,2611.0,2091.0,2633.0,2255.0,2563.0,2662.0,2016.0,2100.0,2821.0,2422.0
Pune Warriors,NaN,NaN,NaN,1674.0,2183.0,2183.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Punjab Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2061.0,2193.0,2416.0,2372.0
Rajasthan Royals,2424.0,1610.0,2072.0,1601.0,2393.0,2571.0,2070.0,2043.0,NaN,NaN,2276.0,2103.0,2197.0,2087.0,2807.0,2287.0,2533.0
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,1865.0,2166.0,2272.0,2325.0,2351.0,2460.0,1992.0,2190.0,2863.0,1760.0,2240.0,2129.0,2169.0,2181.0,2454.0,2393.0,NaN
Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2789.0
Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,2197.0,1943.0,2117.0,2549.0,2262.0,2600.0,2353.0,2397.0,1965.0,2084.0,2268.0,2906.0

` 👉 Rows = teams`

`👉 Columns = seasons`

`👉 Cells = total runs`

##### This is exactly why pivot_table exists.

### Summary(pd.pivot_table())




##### 🧠 ONE FINAL MEMORY LINE (WRITE THIS)


 `If my result should look like an Excel table, I should use pivot_table.`

## 🧪 PIVOT TABLE EXERCISES (IPL DATA)
#### 🟢 Exercise 1 (Very Easy – Warm-up)

#### Question:
`Create a pivot table that shows total runs scored by each batting team.`

#### 📌 Hints:

- values → batsman_runs

- index → batting_team

- aggfunc → sum

In [276]:
# Comparing a metric over a category using pivot_table 
)
pd.pivot_table(
    data=deliveries,
    index="batting_team",
    values="batsman_runs",
    aggfunc="sum"
)

                             batsman_runs
batting_team
Chennai Super Kings                 36739
Deccan Chargers                     10885
Delhi Capitals                      14229
Delhi Daredevils                    23022
Gujarat Lions                        4629
Gujarat Titans                       7357
Kings XI Punjab                     28541
Kochi Tuskers Kerala                 1758
Kolkata Knight Riders               37149
Lucknow Super Giants                 7081
Mumbai Indians                      39946
Pune Warriors                        6040
Punjab Kings                         9042
Rajasthan Royals                    33074
Rising Pune Supergiant               2370
Rising Pune Supergiants              1962
Royal Challengers Bangalore         35810
Royal Challengers Bengaluru          2789
Sunrisers Hyderabad                 27641

#### 🟢 Exercise 2 (Easy)

#### Question:
`Create a pivot table that shows total runs scored by each team in each season.`

#### 📌 Hints:

- You need merged data (deliveries + matches)

- index → batting_team

- columns → season

- values → batsman_runs

In [280]:
# Merging Two Datasets
merged_records=pd.merge (
    deliveries,
    matches,
    left_on="match_id",
    right_on="id"
)

# # Comparing a metric over two categories using pivot_table 
pd.pivot_table(
    data=merged_records,
    index="batting_team",
    values="batsman_runs",
    columns="season",
    aggfunc="sum",
    )

season,2007/08,2009,2009/10,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020/21,2021,2022,2023,2024
batting_team,,,,,,,,,,,,,,,,,
Chennai Super Kings,2365.0,2084.0,2442.0,2461.0,2717.0,2671.0,2519.0,2564.0,NaN,NaN,2698.0,2346.0,2095.0,2607.0,2165.0,2600.0,2405.0
Deccan Chargers,2117.0,2283.0,2244.0,2039.0,2202.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2428.0,2658.0,2387.0,2218.0,2073.0,2465.0
Delhi Daredevils,2000.0,2021.0,2028.0,1942.0,2502.0,2114.0,1978.0,2061.0,1995.0,2131.0,2250.0,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2318.0,2311.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2517.0,2906.0,1934.0
Kings XI Punjab,2340.0,1768.0,2165.0,2080.0,2286.0,2312.0,2824.0,1902.0,2051.0,2099.0,2124.0,2326.0,2264.0,NaN,NaN,NaN,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,1758.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,1801.0,1678.0,1978.0,1905.0,2356.0,2134.0,2382.0,1939.0,2133.0,2354.0,2655.0,2359.0,2124.0,2423.0,2109.0,2338.0,2481.0
Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2405.0,2326.0,2350.0
Mumbai Indians,1897.0,1766.0,2553.0,2143.0,2333.0,2845.0,2235.0,2611.0,2091.0,2633.0,2255.0,2563.0,2662.0,2016.0,2100.0,2821.0,2422.0
Pune Warriors,NaN,NaN,NaN,1674.0,2183.0,2183.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Punjab Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2061.0,2193.0,2416.0,2372.0
Rajasthan Royals,2424.0,1610.0,2072.0,1601.0,2393.0,2571.0,2070.0,2043.0,NaN,NaN,2276.0,2103.0,2197.0,2087.0,2807.0,2287.0,2533.0
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,1865.0,2166.0,2272.0,2325.0,2351.0,2460.0,1992.0,2190.0,2863.0,1760.0,2240.0,2129.0,2169.0,2181.0,2454.0,2393.0,NaN
Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2789.0
Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,2197.0,1943.0,2117.0,2549.0,2262.0,2600.0,2353.0,2397.0,1965.0,2084.0,2268.0,2906.0

#### 🟡 Exercise 3 (Medium)

#### Question:
`Create a pivot table that shows number of sixes hit by each team per season.`

#### 📌 Hints:

- Filter first: batsman_runs == 6

- Use pivot_table

- aggfunc → count or size

In [290]:
# Filtering for six hitting deliveries
six_hitters_records=merged_records[merged_records["batsman_runs"]==6]

# Comparing a metric over two categories using pivot_table  
pd.pivot_table(
    data=six_hitters_records,
    index="batting_team",
    values="batsman_runs",
    columns="season",
    aggfunc="count",
)

season,2007/08,2009,2009/10,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020/21,2021,2022,2023,2024
batting_team,,,,,,,,,,,,,,,,,
Chennai Super Kings,86.0,73.0,98.0,91.0,102.0,84.0,112.0,96.0,NaN,NaN,145.0,89.0,75.0,115.0,103.0,133.0,107.0
Deccan Chargers,92.0,99.0,84.0,48.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,89.0,66.0,106.0,67.0,135.0
Delhi Daredevils,54.0,51.0,58.0,75.0,97.0,52.0,63.0,84.0,65.0,87.0,115.0,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,124.0,68.0
Kings XI Punjab,95.0,61.0,58.0,74.0,61.0,65.0,127.0,79.0,54.0,88.0,104.0,110.0,99.0,NaN,NaN,NaN,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,76.0,56.0,63.0,45.0,69.0,57.0,77.0,64.0,65.0,87.0,130.0,143.0,86.0,98.0,113.0,125.0,141.0
Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,115.0,102.0
Mumbai Indians,76.0,54.0,75.0,57.0,80.0,117.0,86.0,120.0,93.0,118.0,107.0,116.0,137.0,76.0,100.0,140.0,133.0
Pune Warriors,NaN,NaN,NaN,60.0,60.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Punjab Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,110.0,117.0,120.0
Rajasthan Royals,85.0,47.0,74.0,42.0,69.0,70.0,86.0,65.0,NaN,NaN,77.0,66.0,105.0,90.0,137.0,112.0,112.0
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,59.0,67.0,77.0,94.0,118.0,106.0,92.0,105.0,142.0,75.0,106.0,93.0,66.0,79.0,102.0,107.0,NaN
Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0
Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,54.0,72.0,79.0,89.0,70.0,88.0,82.0,79.0,70.0,97.0,84.0,178.0

#### 🟡 Exercise 4 (Medium)

#### Question:
`Create a pivot table that shows average runs per ball for each team.`

#### 📌 Hints:

- values → batsman_runs

- aggfunc → mean

- index → batting_team

In [287]:
# Comparing a metric over two categories using pivot_table  
pd.pivot_table(
    
    data=deliveries,
    index="batting_team",
    values="batsman_runs",
    aggfunc="mean",
)

                             batsman_runs
batting_team
Chennai Super Kings              1.282294
Deccan Chargers                  1.204893
Delhi Capitals                   1.299927
Delhi Daredevils                 1.225487
Gujarat Lions                    1.298093
Gujarat Titans                   1.339097
Kings XI Punjab                  1.260311
Kochi Tuskers Kerala             1.111252
Kolkata Knight Riders            1.258691
Lucknow Super Giants             1.311296
Mumbai Indians                   1.270668
Pune Warriors                    1.109682
Punjab Kings                     1.323284
Rajasthan Royals                 1.260346
Rising Pune Supergiant           1.247368
Rising Pune Supergiants          1.241772
Royal Challengers Bangalore      1.269633
Royal Challengers Bengaluru      1.534103
Sunrisers Hyderabad              1.265440

#### 🔵 Exercise 5 (Challenge – Think Carefully)

#### Question:
`Create a pivot table that shows Virat Kohli’s total runs per season.`

#### 📌 Hints:

- Filter batter = "V Kohli"

- columns → season

- values → runs

- aggfunc → sum

In [289]:
# Filtering Logic
kohli_records=merged_records[merged_records["batter"]=="V Kohli"]


pd.pivot_table(
    data=kohli_records,
    index="batter",
    values="batsman_runs",
    columns="season",
    aggfunc="sum",
    )

season,2007/08,2009,2009/10,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020/21,2021,2022,2023,2024
batter,,,,,,,,,,,,,,,,,
V Kohli,165,246,307,557,364,639,359,505,973,308,530,464,471,405,341,639,741

#### ⭐ Pivot Table (`pd.pivot_table`) — Overall Evaluation

### 📊 Final Rating: **9.8 / 10**

---

#### ✅ What You Did Exceptionally Well

- ✔ **Correct Conceptual Understanding**
  - You clearly understood *when* and *why* to use `pivot_table`
  - You used it for **comparison-based analysis**, not simple ranking

- ✔ **Proper Use of Parameters**
  - Correct usage of:
    - `values`
    - `index`
    - `columns`
    - `aggfunc`
  - Clean and readable structure in every task

- ✔ **Right Analytical Thinking**
  - Filtered data **before** pivoting (e.g., six-hitting analysis)
  - Chose appropriate aggregation (`sum`, `mean`, `count`)
  - Used merged data correctly for season-wise analysis

- ✔ **Real-World Use Cases**
  - Team vs Season analysis
  - Player (Virat Kohli) season-wise performance
  - Six-hitting trends across teams and seasons  
  These are **portfolio-level analyses**, not practice-only code.

---

#### 🔧 Minor Improvements (Very Small)

- In one task, `count` was used where `size` could be slightly more precise  
  *(Not wrong — just a micro-optimization)*

---

#### 🧠 One-Line Concept Summary (Notebook Worthy)

> **`pd.pivot_table()` is used when we want to compare one metric across two categories and present the result in a row–column table format, similar to an Excel Pivot Table.**

---

#### 🏁 Final Verdict

- You have **fully mastered `pivot_table()`**
- Your understanding is **conceptual, not memorized**
- You are using Pandas like a **Junior Data Analyst**

---

#### ✅ Status Update
`pd.pivot_table()` → **MASTERED ✔**

#### 🔵 FUNCTION 1: .set_index() (VERY SIMPLE CONCEPT)

--- 

**✍️ Write this:**

**`Use set_index() when a column uniquely identifies each row and is not meant for calculations.`**

#### 🟦 Example 1: .set_index() (Simple & Clear)
#### **🎯 Goal**

**Make the table cleaner and more readable by using batter as row identity**

In [296]:
data = merged_records.set_index("batting_team")
data.head()

,match_id,inning,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
batting_team,,,,,,,,,,,,,,,,,,,,,
Kolkata Knight Riders,335982,1,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
Kolkata Knight Riders,335982,1,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
Kolkata Knight Riders,335982,1,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
Kolkata Knight Riders,335982,1,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
Kolkata Knight Riders,335982,1,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

#### 🧠 Why this is good

##### - Batter name is an identifier, not data

##### - Table looks professional

##### - Easier to read and reference

**✍️ Memory Line**

>Use set_index() when a column is an identity, not a metric.

#### 🔵 FUNCTION 2: .apply() (MOST MISUSED, SO LISTEN CAREFULLY)

**🧠 What `.apply()` does (IN ONE LINE)**

- apply() applies your custom logic to each value or row.

---

**✍️ Write this:**

`**If Pandas can do it, don’t use apply().
Use apply() only when Pandas cannot.**`

#### 🟦 Example 2: .apply() (Safe & Beginner-Friendly)
#### 🎯 Goal

**Classify each delivery as Boundary or Non-Boundary.**

**This logic cannot be done with groupby or sum.**

**Step 1: Define your custom logic**

In [297]:
def boundary_type(runs):
    if runs == 4 or runs == 6:
        return "Boundary"
    else:
        return "Non-Boundary"

**Step 2: Apply it to the column**

In [300]:
deliveries["run_type"] = deliveries["batsman_runs"].apply(boundary_type)
deliveries[["batsman_runs", "run_type"]].head()

   batsman_runs      run_type
0             0  Non-Boundary
1             0  Non-Boundary
2             0  Non-Boundary
3             0  Non-Boundary
4             0  Non-Boundary

#### ⚠️ Important Rule (Write This)

>**If Pandas already has a function, do not use apply().**
---


 ### `Alhumdullah Roadmap Completed of Pandas Library of Python `