# Pandas(The Data Handling  Tool):

#### It is built  on  top of NumPy
#### What field is it used in?
- Data Analysis
- Data Science
- Machine Learning 
#### Here we only or mostly deals with the data in "Series"  and "DataFrame"
#### Through Pandas we can import ,Display ,manipulate and Export Tabular data

In [3]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\umair\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\umair\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\umair\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\umair\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\umair\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\umair\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
import pandas as pd

print(pd.__version__)

2.2.2

# Series:

data=[100,102,102,103,200,201,202,203,304,205]
print("In List format :",data)
series=pd.Series(data)
print("In Series Format : ")
print(series)

In [11]:
data=[True,False]
print("In List format :",data)
series=pd.Series(data)
print("In Series Format : ")
print(series)

In List format : [True, False]
In Series Format :
0     True
1    False
dtype: bool

## Changing indexs from numbers to alphabets:

In [72]:
data=[100,102,102,103,200,201,202,203,304,205]
print("In List format :",data)
series=pd.Series(data,index=['a','b','c','d','e','f','g','h','i','j'])
print("In Series Format : ")
print(series)

In List format : [100, 102, 102, 103, 200, 201, 202, 203, 304, 205]
In Series Format :
a    100
b    102
c    102
d    103
e    200
f    201
g    202
h    203
i    304
j    205
dtype: int64

In [73]:
print(series.loc['a'])

100

In [74]:
series.loc['a']=5300
print(series)

a    5300
b     102
c     102
d     103
e     200
f     201
g     202
h     203
i     304
j     205
dtype: int64

In [75]:
print(series.loc['a':'j'])

a    5300
b     102
c     102
d     103
e     200
f     201
g     202
h     203
i     304
j     205
dtype: int64

In [76]:
print(series.iloc[0])

5300

In [77]:
series.iloc[5]=5300
print(series)

a    5300
b     102
c     102
d     103
e     200
f    5300
g     202
h     203
i     304
j     205
dtype: int64

In [ ]:
print("Printing all rows using Multi_indexing Method")
print(series.iloc[0:10])

# Exersise:

In [94]:
student_names=['Umair','Robert','Jofery','Lily','Rony']
series=pd.Series(student_names,index=['A','B','C','D','E'])
print(series)

A     Umair
B    Robert
C    Jofery
D      Lily
E      Rony
dtype: object

In [102]:
print("At Index A Student is:",series.loc["A"])

At Index A Student is: Umair

In [103]:
print("From index A and D students are:")
print(series.loc["A":"D"])

From index A and D students are:
A     Umair
B    Robert
C    Jofery
D      Lily
dtype: object

In [104]:
#Changing Index A student name
series.loc['A']="Mohammad Umair Hafeez"
print(series.loc['A'])

Mohammad Umair Hafeez

In [107]:
print("At Index 0 Student is:",series.iloc[0])

At Index 0 Student is: Mohammad Umair Hafeez

In [114]:
print("From index 0 and 4 students are:")
print(series.iloc[0:4])

From index 0 and 3 students are:
A    Mohammad Umair Hafeez
B                   Robert
C                   Jofery
D                     Lily
dtype: object

In [116]:
#Changing Index A student name
series.iloc[0]="Mohammad Umair Hafeez"
print(series.iloc[0])

Mohammad Umair Hafeez

In [119]:
print("After some Modification the Series becomes:")
print(series)

After some Modification the Series becomes:
A    Mohammad Umair Hafeez
B                   Robert
C                   Jofery
D                     Lily
E                     Rony
dtype: object

# Conditioning :

In [122]:
data=[10,20,30,40,50,60,70,80,90,100]
series=pd.Series(data,index=['A','B','C','D','E','F','G','H','I','J'])
print(series[series==100])

J    100
dtype: int64

In [127]:
print(series[series>30])

D     40
E     50
F     60
G     70
H     80
I     90
J    100
dtype: int64

In [135]:
print(series[(series==100)|(series==10)])

A     10
J    100
dtype: int64

# Exersise

In [136]:
calories={"Day 1":1750,"Day 2":2100,"Day 3":1700,"Day 4":1800,"Day 5":1900}
series=pd.Series(calories)
print(series)

Day 1:    1750
Day 2     2100
Day 3     1700
Day 4     1800
Day 5     1900
dtype: int64

In [137]:
print(series.loc["Day 3"])

1700

In [140]:
series.loc["Day 2"]+=2500
print(series)

Day 1:     1750
Day 2     15200
Day 3      1700
Day 4      1800
Day 5      1900
dtype: int64

In [144]:
# Days when i folow my diets
print(series[series<2000])

Day 1:    1750
Day 3     1700
Day 4     1800
Day 5     1900
dtype: int64

In [145]:
# Days when i not folow my diets
print(series[series>=2000])

Day 2    15200
dtype: int64

# DataFrame:

### A Tabular data Structure with rows and columns (2 Dimensional) Similar to an Excel Spread Sheet

In [153]:
data={"Name":["Umair","Tomy","Robert"],"Age":[20,21,22]}

df=pd.DataFrame(data,index=["Employee 1","Employee 2","Employee 3"])
print(df)

              Name  Age
Employee 1   Umair   20
Employee 2    Tomy   21
Employee 3  Robert   22

In [163]:
# Accessing Specific  Index Value
print(df.loc["Employee 1"])

Name    Umair
Age        20
Name: Employee 1, dtype: object

In [164]:
# Accessing Specific  Index Value
print(df.loc["Employee 2"])

Name    Tomy
Age       21
Name: Employee 2, dtype: object

In [165]:
# Accessing Specific  Index Value
print(df.loc["Employee 3"])

Name    Robert
Age         22
Name: Employee 3, dtype: object

In [161]:
# Accessing Specific  Index Value 
print(df.iloc[0])

Name    Umair
Age        20
Name: Employee 1, dtype: object

### Adding New Columns

In [168]:
# How to add new column :
df['Job']=['Data Anayst',"N/A","Cashier"]
print(df)

              Name  Age          Job        Country
Employee 1   Umair   20  Data Anayst       Pakistan
Employee 2    Tomy   21          N/A  United Kindom
Employee 3  Robert   22      Cashier         Canada

In [169]:
#  Adding  new Column :
df['Country']=['Pakistan','United Kindom','Canada']
print(df)

              Name  Age          Job        Country
Employee 1   Umair   20  Data Anayst       Pakistan
Employee 2    Tomy   21          N/A  United Kindom
Employee 3  Robert   22      Cashier         Canada

In [170]:
# Adding new Column name of City
df['City']=['Quetta','Karachi ','Islamabad']
print(df)

              Name  Age          Job        Country       City
Employee 1   Umair   20  Data Anayst       Pakistan     Quetta
Employee 2    Tomy   21          N/A  United Kindom   Karachi
Employee 3  Robert   22      Cashier         Canada  Islamabad

### Adding New Rows

In [174]:
new_row=pd.DataFrame([{"Name":"Mexcy","Age":25,"Job":"Data Scientist","Country":"America","City":"NewYork"}],index=["Employee 4"])
print(new_row)

             Name  Age             Job  Country     City
Employee 4  Mexcy   25  Data Scientist  America  NewYork

In [176]:
df=pd.concat([df,new_row])
print(df)

              Name  Age             Job        Country       City
Employee 1   Umair   20     Data Anayst       Pakistan     Quetta
Employee 2    Tomy   21             N/A  United Kindom   Karachi
Employee 3  Robert   22         Cashier         Canada  Islamabad
Employee 4   Mexcy   25  Data Scientist        America    NewYork

## Exersise
- Create Record for students Data Science subject their Name,ID,Class,Sections,total_marks,obtained_marks,Status

In [204]:
data={"Name":["Umair Baloch","Irfan Khan","Robert","Mexy","Lily","Mike","Shoaib"],"ID":[1711,1712,1713,1714,1715,1716,1717],"Class":[1,1,1,1,1,1,1],"Section":['A','A','A','A','B','B','B'],"Total_Marks":[100,100,100,100,100,100,100],"Obtained_Marks":[98,76,87,98,46,45,99],"Status":["Pass",'Pass','Pass','Pass','Fail','Fail','Pass']}
df=pd.DataFrame(data,index=[1,2,3,4,5,6,7])
df

           Name    ID  Class Section  Total_Marks  Obtained_Marks Status
1  Umair Baloch  1711      1       A          100              98   Pass
2    Irfan Khan  1712      1       A          100              76   Pass
3        Robert  1713      1       A          100              87   Pass
4          Mexy  1714      1       A          100              98   Pass
5          Lily  1715      1       B          100              46   Fail
6          Mike  1716      1       B          100              45   Fail
7        Shoaib  1717      1       B          100              99   Pass

In [205]:
print(df.loc[1:5])

           Name    ID  Class Section  Total_Marks  Obtained_Marks Status
1  Umair Baloch  1711      1       A          100              98   Pass
2    Irfan Khan  1712      1       A          100              76   Pass
3        Robert  1713      1       A          100              87   Pass
4          Mexy  1714      1       A          100              98   Pass
5          Lily  1715      1       B          100              46   Fail

In [206]:
print(df.iloc[0:5])

           Name    ID  Class Section  Total_Marks  Obtained_Marks Status
1  Umair Baloch  1711      1       A          100              98   Pass
2    Irfan Khan  1712      1       A          100              76   Pass
3        Robert  1713      1       A          100              87   Pass
4          Mexy  1714      1       A          100              98   Pass
5          Lily  1715      1       B          100              46   Fail

In [207]:
# Adding  New Columns
df["Personality_Status"]=["Good","Okay ","Normal","Casual","Too Bad","Best","Good"]
df

,Name,ID,Class,Section,Total_Marks,Obtained_Marks,Status,Personality_Status
1,Umair Baloch,1711,1,A,100,98,Pass,Good
2,Irfan Khan,1712,1,A,100,76,Pass,Okay
3,Robert,1713,1,A,100,87,Pass,Normal
4,Mexy,1714,1,A,100,98,Pass,Casual
5,Lily,1715,1,B,100,46,Fail,Too Bad
6,Mike,1716,1,B,100,45,Fail,Best
7,Shoaib,1717,1,B,100,99,Pass,Good

In [208]:
# Creating New Row (DataFrame)
data={"Name":"Nany","ID":1718,"Class":2,"Section":"C","Total_Marks":100,"Obtained_Marks":22,"Status":"Fail","Personality_Status":"Best"}
new_row=pd.DataFrame(data,index=[8])
new_row

,Name,ID,Class,Section,Total_Marks,Obtained_Marks,Status,Personality_Status
8,Nany,1718,2,C,100,22,Fail,Best

In [210]:
# Adding New Row to Existed one
df=pd.concat([df,new_row])
df

,Name,ID,Class,Section,Total_Marks,Obtained_Marks,Status,Personality_Status
8,Nany,1718,2,C,100,22,Fail,Best
1,Umair Baloch,1711,1,A,100,98,Pass,Good
2,Irfan Khan,1712,1,A,100,76,Pass,Okay
3,Robert,1713,1,A,100,87,Pass,Normal
4,Mexy,1714,1,A,100,98,Pass,Casual
5,Lily,1715,1,B,100,46,Fail,Too Bad
6,Mike,1716,1,B,100,45,Fail,Best
7,Shoaib,1717,1,B,100,99,Pass,Good
8,Nany,1718,2,C,100,22,Fail,Best

# Importing CSV and JSon Files

In [218]:
import pandas as pd

df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv")
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [219]:
# Printing all rows(only Esential if dataset is small) 
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       Bug       NaN     0.3     2.9          0
10    11     Metapod       Bug       NaN     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       NaN     0.3     3.5          0
19    20    Raticate    Normal       NaN     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       NaN     2.0     6.9          0
23    24       Arbok    Poison       NaN     3.5    65.0          0
24    25     Pikachu  Electric       NaN     0.4     6.0          0
25    26      Raichu  Electric       NaN     0.8    30.0          0
26    27   Sandshrew    Ground       NaN     0.6    12.0          0
27    28   Sandslash    Ground       NaN     1.0    29.5          0
28    29    Nidoran♀    Poison       NaN     0.4     7.0          0
29    30    Nidorina    Poison       NaN     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       NaN     0.5     9.0          0
32    33    Nidorino    Poison       NaN     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       NaN     0.6     7.5          0
35    36    Clefable     Fairy       NaN     1.3    40.0          0
36    37      Vulpix      Fire       NaN     0.6     9.9          0
37    38   Ninetales      Fire       NaN     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       NaN     0.2     0.8          0
50    51     Dugtrio    Ground       NaN     0.7    33.3          0
51    52      Meowth    Normal       NaN     0.4     4.2          0
52    53     Persian    Normal       NaN     1.0    32.0          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
55    56      Mankey  Fighting       NaN     0.5    28.0          0
56    57    Primeape  Fighting       NaN     1.0    32.0          0
57    58   Growlithe      Fire       NaN     0.7    19.0          0
58    59    Arcanine      Fire       NaN     1.9   155.0          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       NaN     0.9    19.5          0
63    64     Kadabra   Psychic       NaN     1.3    56.5          0
64    65    Alakazam   Psychic       NaN     1.5    48.0          0
65    66      Machop  Fighting       NaN     0.8    19.5          0
66    67     Machoke  Fighting       NaN     1.5    70.5          0
67    68     Machamp  Fighting       NaN     1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       NaN     1.0    30.0          0
77    78    Rapidash      Fire       NaN     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       NaN     0.9    30.0          0
88    89         Muk    Poison       NaN     1.2    30.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       NaN     1.0    32.4          0
96    97       Hypno   Psychic       NaN     1.6    75.6          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
99   100     Voltorb  Electric       NaN     0.5    10.4          0
100  101   Electrode  Electric       NaN     1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground       NaN     0.4     6.5          0
104  105     Marowak    Ground       NaN     1.0    45.0          0
105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
107  108   Lickitung    Normal       NaN     1.2    65.5          0
108  109     Koffing    Poison       NaN     0.6     1.0          0
109  110     Weezing    Poison       NaN     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       NaN     1.1    34.6          0
113  114     Tangela     Grass       NaN     1.0    35.0          0
114  115  Kangaskhan    Normal       NaN     2.2    80.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       NaN     1.1    30.0          0
125  126      Magmar      Fire       NaN     1.3    44.5          0
126  127      Pinsir       Bug       NaN     1.5    55.0          0
127  128      Tauros    Normal       NaN     1.4    88.4          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       NaN     0.3     4.0          0
132  133       Eevee    Normal       NaN     0.3     6.5          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
134  135     Jolteon  Electric       NaN     0.8    24.5          0
135  136     Flareon      Fire       NaN     0.9    25.0          0
136  137     Porygon    Normal       NaN     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       NaN     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       NaN     1.8     3.3          0
147  148   Dragonair    Dragon       NaN     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1

# Selection

In [224]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="Name")
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [244]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="Name")
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [225]:
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       Bug       NaN     0.3     2.9          0
10    11     Metapod       Bug       NaN     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       NaN     0.3     3.5          0
19    20    Raticate    Normal       NaN     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       NaN     2.0     6.9          0
23    24       Arbok    Poison       NaN     3.5    65.0          0
24    25     Pikachu  Electric       NaN     0.4     6.0          0
25    26      Raichu  Electric       NaN     0.8    30.0          0
26    27   Sandshrew    Ground       NaN     0.6    12.0          0
27    28   Sandslash    Ground       NaN     1.0    29.5          0
28    29    Nidoran♀    Poison       NaN     0.4     7.0          0
29    30    Nidorina    Poison       NaN     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       NaN     0.5     9.0          0
32    33    Nidorino    Poison       NaN     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       NaN     0.6     7.5          0
35    36    Clefable     Fairy       NaN     1.3    40.0          0
36    37      Vulpix      Fire       NaN     0.6     9.9          0
37    38   Ninetales      Fire       NaN     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       NaN     0.2     0.8          0
50    51     Dugtrio    Ground       NaN     0.7    33.3          0
51    52      Meowth    Normal       NaN     0.4     4.2          0
52    53     Persian    Normal       NaN     1.0    32.0          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
55    56      Mankey  Fighting       NaN     0.5    28.0          0
56    57    Primeape  Fighting       NaN     1.0    32.0          0
57    58   Growlithe      Fire       NaN     0.7    19.0          0
58    59    Arcanine      Fire       NaN     1.9   155.0          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       NaN     0.9    19.5          0
63    64     Kadabra   Psychic       NaN     1.3    56.5          0
64    65    Alakazam   Psychic       NaN     1.5    48.0          0
65    66      Machop  Fighting       NaN     0.8    19.5          0
66    67     Machoke  Fighting       NaN     1.5    70.5          0
67    68     Machamp  Fighting       NaN     1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       NaN     1.0    30.0          0
77    78    Rapidash      Fire       NaN     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       NaN     0.9    30.0          0
88    89         Muk    Poison       NaN     1.2    30.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       NaN     1.0    32.4          0
96    97       Hypno   Psychic       NaN     1.6    75.6          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
99   100     Voltorb  Electric       NaN     0.5    10.4          0
100  101   Electrode  Electric       NaN     1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground       NaN     0.4     6.5          0
104  105     Marowak    Ground       NaN     1.0    45.0          0
105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
107  108   Lickitung    Normal       NaN     1.2    65.5          0
108  109     Koffing    Poison       NaN     0.6     1.0          0
109  110     Weezing    Poison       NaN     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       NaN     1.1    34.6          0
113  114     Tangela     Grass       NaN     1.0    35.0          0
114  115  Kangaskhan    Normal       NaN     2.2    80.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       NaN     1.1    30.0          0
125  126      Magmar      Fire       NaN     1.3    44.5          0
126  127      Pinsir       Bug       NaN     1.5    55.0          0
127  128      Tauros    Normal       NaN     1.4    88.4          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       NaN     0.3     4.0          0
132  133       Eevee    Normal       NaN     0.3     6.5          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
134  135     Jolteon  Electric       NaN     0.8    24.5          0
135  136     Flareon      Fire       NaN     0.9    25.0          0
136  137     Porygon    Normal       NaN     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       NaN     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       NaN     1.8     3.3          0
147  148   Dragonair    Dragon       NaN     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1

In [234]:
# Accessing Cmplete Name Column or single Column
print(df["Name"].to_string())

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
5       Charizard
6        Squirtle
7       Wartortle
8       Blastoise
9        Caterpie
10        Metapod
11     Butterfree
12         Weedle
13         Kakuna
14       Beedrill
15         Pidgey
16      Pidgeotto
17        Pidgeot
18        Rattata
19       Raticate
20        Spearow
21         Fearow
22          Ekans
23          Arbok
24        Pikachu
25         Raichu
26      Sandshrew
27      Sandslash
28       Nidoran♀
29       Nidorina
30      Nidoqueen
31       Nidoran♂
32       Nidorino
33       Nidoking
34       Clefairy
35       Clefable
36         Vulpix
37      Ninetales
38     Jigglypuff
39     Wigglytuff
40          Zubat
41         Golbat
42         Oddish
43          Gloom
44      Vileplume
45          Paras
46       Parasect
47        Venonat
48       Venomoth
49        Diglett
50        Dugtrio
51         Meowth
52        Persian
53        Psyduck
54        Golduck
55         Mankey
56       Primeape
57      Growlithe
58       Arcanine
59        Poliwag
60      Poliwhirl
61      Poliwrath
62           Abra
63        Kadabra
64       Alakazam
65         Machop
66        Machoke
67        Machamp
68     Bellsprout
69     Weepinbell
70     Victreebel
71      Tentacool
72     Tentacruel
73        Geodude
74       Graveler
75          Golem
76         Ponyta
77       Rapidash
78       Slowpoke
79        Slowbro
80      Magnemite
81       Magneton
82     Farfetch'd
83          Doduo
84         Dodrio
85           Seel
86        Dewgong
87         Grimer
88            Muk
89       Shellder
90       Cloyster
91         Gastly
92        Haunter
93         Gengar
94           Onix
95        Drowzee
96          Hypno
97         Krabby
98        Kingler
99        Voltorb
100     Electrode
101     Exeggcute
102     Exeggutor
103        Cubone
104       Marowak
105     Hitmonlee
106    Hitmonchan
107     Lickitung
108       Koffing
109       Weezing
110       Rhyhorn
111        Rhydon
112       Chansey
113       Tangela
114    Kangaskhan
115        Horsea
116        Seadra
117       Goldeen
118       Seaking
119        Staryu
120       Starmie
121      Mr. Mime
122       Scyther
123          Jynx
124    Electabuzz
125        Magmar
126        Pinsir
127        Tauros
128      Magikarp
129      Gyarados
130        Lapras
131         Ditto
132         Eevee
133      Vaporeon
134       Jolteon
135       Flareon
136       Porygon
137       Omanyte
138       Omastar
139        Kabuto
140      Kabutops
141    Aerodactyl
142       Snorlax
143      Articuno
144        Zapdos
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo

In [ ]:
print(df["Name"].head())

In [ ]:
print(df["Name"].tail())

In [237]:
# Accessing Multiple Column  
print(df[["No","Name","Type1"]])

      No        Name    Type1
0      1   Bulbasaur    Grass
1      2     Ivysaur    Grass
2      3    Venusaur    Grass
3      4  Charmander     Fire
4      5  Charmeleon     Fire
..   ...         ...      ...
145  146     Moltres     Fire
146  147     Dratini   Dragon
147  148   Dragonair   Dragon
148  149   Dragonite   Dragon
149  150      Mewtwo  Psychic

[150 rows x 3 columns]

In [242]:
print(df[["No","Name","Type1"]].to_string())

      No        Name     Type1
0      1   Bulbasaur     Grass
1      2     Ivysaur     Grass
2      3    Venusaur     Grass
3      4  Charmander      Fire
4      5  Charmeleon      Fire
5      6   Charizard      Fire
6      7    Squirtle     Water
7      8   Wartortle     Water
8      9   Blastoise     Water
9     10    Caterpie       Bug
10    11     Metapod       Bug
11    12  Butterfree       Bug
12    13      Weedle       Bug
13    14      Kakuna       Bug
14    15    Beedrill       Bug
15    16      Pidgey    Normal
16    17   Pidgeotto    Normal
17    18     Pidgeot    Normal
18    19     Rattata    Normal
19    20    Raticate    Normal
20    21     Spearow    Normal
21    22      Fearow    Normal
22    23       Ekans    Poison
23    24       Arbok    Poison
24    25     Pikachu  Electric
25    26      Raichu  Electric
26    27   Sandshrew    Ground
27    28   Sandslash    Ground
28    29    Nidoran♀    Poison
29    30    Nidorina    Poison
30    31   Nidoqueen    Poison
31    32    Nidoran♂    Poison
32    33    Nidorino    Poison
33    34    Nidoking    Poison
34    35    Clefairy     Fairy
35    36    Clefable     Fairy
36    37      Vulpix      Fire
37    38   Ninetales      Fire
38    39  Jigglypuff    Normal
39    40  Wigglytuff    Normal
40    41       Zubat    Poison
41    42      Golbat    Poison
42    43      Oddish     Grass
43    44       Gloom     Grass
44    45   Vileplume     Grass
45    46       Paras       Bug
46    47    Parasect       Bug
47    48     Venonat       Bug
48    49    Venomoth       Bug
49    50     Diglett    Ground
50    51     Dugtrio    Ground
51    52      Meowth    Normal
52    53     Persian    Normal
53    54     Psyduck     Water
54    55     Golduck     Water
55    56      Mankey  Fighting
56    57    Primeape  Fighting
57    58   Growlithe      Fire
58    59    Arcanine      Fire
59    60     Poliwag     Water
60    61   Poliwhirl     Water
61    62   Poliwrath     Water
62    63        Abra   Psychic
63    64     Kadabra   Psychic
64    65    Alakazam   Psychic
65    66      Machop  Fighting
66    67     Machoke  Fighting
67    68     Machamp  Fighting
68    69  Bellsprout     Grass
69    70  Weepinbell     Grass
70    71  Victreebel     Grass
71    72   Tentacool     Water
72    73  Tentacruel     Water
73    74     Geodude      Rock
74    75    Graveler      Rock
75    76       Golem      Rock
76    77      Ponyta      Fire
77    78    Rapidash      Fire
78    79    Slowpoke     Water
79    80     Slowbro     Water
80    81   Magnemite  Electric
81    82    Magneton  Electric
82    83  Farfetch'd    Normal
83    84       Doduo    Normal
84    85      Dodrio    Normal
85    86        Seel     Water
86    87     Dewgong     Water
87    88      Grimer    Poison
88    89         Muk    Poison
89    90    Shellder     Water
90    91    Cloyster     Water
91    92      Gastly     Ghost
92    93     Haunter     Ghost
93    94      Gengar     Ghost
94    95        Onix      Rock
95    96     Drowzee   Psychic
96    97       Hypno   Psychic
97    98      Krabby     Water
98    99     Kingler     Water
99   100     Voltorb  Electric
100  101   Electrode  Electric
101  102   Exeggcute     Grass
102  103   Exeggutor     Grass
103  104      Cubone    Ground
104  105     Marowak    Ground
105  106   Hitmonlee  Fighting
106  107  Hitmonchan  Fighting
107  108   Lickitung    Normal
108  109     Koffing    Poison
109  110     Weezing    Poison
110  111     Rhyhorn    Ground
111  112      Rhydon    Ground
112  113     Chansey    Normal
113  114     Tangela     Grass
114  115  Kangaskhan    Normal
115  116      Horsea     Water
116  117      Seadra     Water
117  118     Goldeen     Water
118  119     Seaking     Water
119  120      Staryu     Water
120  121     Starmie     Water
121  122    Mr. Mime   Psychic
122  123     Scyther       Bug
123  124        Jynx       Ice
124  125  Electabuzz  Electric
125  126      Magmar      Fire
126  127      Pinsir       Bug
127  128      Tauros    Normal
128  129    Magikarp     Water
129  130    Gyarados     Water
130  131      Lapras     Water
131  132       Ditto    Normal
132  133       Eevee    Normal
133  134    Vaporeon     Water
134  135     Jolteon  Electric
135  136     Flareon      Fire
136  137     Porygon    Normal
137  138     Omanyte      Rock
138  139     Omastar      Rock
139  140      Kabuto      Rock
140  141    Kabutops      Rock
141  142  Aerodactyl      Rock
142  143     Snorlax    Normal
143  144    Articuno       Ice
144  145      Zapdos  Electric
145  146     Moltres      Fire
146  147     Dratini    Dragon
147  148   Dragonair    Dragon
148  149   Dragonite    Dragon
149  150      Mewtwo   Psychic

In [238]:
print(df[["No","Name","Type1"]].head())

   No        Name  Type1
0   1   Bulbasaur  Grass
1   2     Ivysaur  Grass
2   3    Venusaur  Grass
3   4  Charmander   Fire
4   5  Charmeleon   Fire

In [239]:
print(df[["No","Name","Type1"]].tail())

      No       Name    Type1
145  146    Moltres     Fire
146  147    Dratini   Dragon
147  148  Dragonair   Dragon
148  149  Dragonite   Dragon
149  150     Mewtwo  Psychic

### Selection by Row

In [248]:
print(df.loc["Bulbasaur"])

No                1
Type1         Grass
Type2        Poison
Height          0.7
Weight          6.9
Legendary         0
Name: Bulbasaur, dtype: object

In [256]:
print(df.loc["Bulbasaur",["Height","Weight","Type1","Type2"]])

Height       0.7
Weight       6.9
Type1      Grass
Type2     Poison
Name: Bulbasaur, dtype: object

In [249]:
print(df.loc["Bulbasaur":"Charmeleon"])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Ivysaur      2  Grass  Poison     1.0    13.0          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmander   4   Fire     NaN     0.6     8.5          0
Charmeleon   5   Fire     NaN     1.1    19.0          0

In [257]:
print(df.loc["Bulbasaur":"Charmeleon",["Type1","Type2"]])

            Type1   Type2
Name
Bulbasaur   Grass  Poison
Ivysaur     Grass  Poison
Venusaur    Grass  Poison
Charmander   Fire     NaN
Charmeleon   Fire     NaN

In [262]:
print(df.iloc[0:10])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Ivysaur      2  Grass  Poison     1.0    13.0          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmander   4   Fire     NaN     0.6     8.5          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Charizard    6   Fire  Flying     1.7    90.5          0
Squirtle     7  Water     NaN     0.5     9.0          0
Wartortle    8  Water     NaN     1.0    22.5          0
Blastoise    9  Water     NaN     1.6    85.5          0
Caterpie    10    Bug     NaN     0.3     2.9          0

In [263]:
print(df.iloc[0:10:2])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Squirtle     7  Water     NaN     0.5     9.0          0
Blastoise    9  Water     NaN     1.6    85.5          0

In [270]:
# little Advance
print(df.iloc[0:10:2,0:5])

            No  Type1   Type2  Height  Weight
Name
Bulbasaur    1  Grass  Poison     0.7     6.9
Venusaur     3  Grass  Poison     2.0   100.0
Charmeleon   5   Fire     NaN     1.1    19.0
Squirtle     7  Water     NaN     0.5     9.0
Blastoise    9  Water     NaN     1.6    85.5

# Exersise

In [282]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="Name")
Pokemon=input(print("Enter the Name of your Pokemon from the the given Dataset  :"))

try :
    print(f"{Pokemon} Pokemon Found :",)
except KeyError:
    print(f"{Pokemon} Pokemon Not Found")

Enter the Name of your Pokemon from the the given Dataset  :

None Bulbasaur

Bulbasaur Pokemon Found :

# Filtering :

In [312]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="No")

In [313]:
tall_pokemon=(df[df["Height"]>=2])
print(tall_pokemon)

           Name    Type1    Type2  Height  Weight  Legendary
No
3      Venusaur    Grass   Poison     2.0   100.0          0
23        Ekans   Poison      NaN     2.0     6.9          0
24        Arbok   Poison      NaN     3.5    65.0          0
95         Onix     Rock   Ground     8.8   210.0          0
103   Exeggutor    Grass  Psychic     2.0   120.0          0
115  Kangaskhan   Normal      NaN     2.2    80.0          0
130    Gyarados    Water   Flying     6.5   235.0          0
131      Lapras    Water      Ice     2.5   220.0          0
143     Snorlax   Normal      NaN     2.1   460.0          0
146     Moltres     Fire   Flying     2.0    60.0          1
148   Dragonair   Dragon      NaN     4.0    16.5          0
149   Dragonite   Dragon   Flying     2.2   210.0          0
150      Mewtwo  Psychic      NaN     2.0   122.0          1

In [ ]:
tall_pokemon=(df[df["Height"]<=2]).to_string()
print(tall_pokemon)

In [297]:
heavy_pokemon=(df[df["Weight"]>=100])
print(heavy_pokemon)

          Name     Type1    Type2  Height  Weight  Legendary
No
3     Venusaur     Grass   Poison     2.0   100.0          0
59    Arcanine      Fire      NaN     1.9   155.0          0
68     Machamp  Fighting      NaN     1.6   130.0          0
75    Graveler      Rock   Ground     1.0   105.0          0
76       Golem      Rock   Ground     1.4   300.0          0
87     Dewgong     Water      Ice     1.7   120.0          0
91    Cloyster     Water      Ice     1.5   132.5          0
95        Onix      Rock   Ground     8.8   210.0          0
103  Exeggutor     Grass  Psychic     2.0   120.0          0
111    Rhyhorn    Ground     Rock     1.0   115.0          0
112     Rhydon    Ground     Rock     1.9   120.0          0
130   Gyarados     Water   Flying     6.5   235.0          0
131     Lapras     Water      Ice     2.5   220.0          0
143    Snorlax    Normal      NaN     2.1   460.0          0
149  Dragonite    Dragon   Flying     2.2   210.0          0
150     Mewtwo   Psychic      NaN     2.0   122.0          1

In [302]:
heavy_pokemon=(df[df["Weight"]<=100]).to_string()
print(heavy_pokemon)

           Name     Type1     Type2  Height  Weight  Legendary
No
1     Bulbasaur     Grass    Poison     0.7     6.9          0
2       Ivysaur     Grass    Poison     1.0    13.0          0
3      Venusaur     Grass    Poison     2.0   100.0          0
4    Charmander      Fire       NaN     0.6     8.5          0
5    Charmeleon      Fire       NaN     1.1    19.0          0
6     Charizard      Fire    Flying     1.7    90.5          0
7      Squirtle     Water       NaN     0.5     9.0          0
8     Wartortle     Water       NaN     1.0    22.5          0
9     Blastoise     Water       NaN     1.6    85.5          0
10     Caterpie       Bug       NaN     0.3     2.9          0
11      Metapod       Bug       NaN     0.7     9.9          0
12   Butterfree       Bug    Flying     1.1    32.0          0
13       Weedle       Bug    Poison     0.3     3.2          0
14       Kakuna       Bug    Poison     0.6    10.0          0
15     Beedrill       Bug    Poison     1.0    29.5          0
16       Pidgey    Normal    Flying     0.3     1.8          0
17    Pidgeotto    Normal    Flying     1.1    30.0          0
18      Pidgeot    Normal    Flying     1.5    39.5          0
19      Rattata    Normal       NaN     0.3     3.5          0
20     Raticate    Normal       NaN     0.7    18.5          0
21      Spearow    Normal    Flying     0.3     2.0          0
22       Fearow    Normal    Flying     1.2    38.0          0
23        Ekans    Poison       NaN     2.0     6.9          0
24        Arbok    Poison       NaN     3.5    65.0          0
25      Pikachu  Electric       NaN     0.4     6.0          0
26       Raichu  Electric       NaN     0.8    30.0          0
27    Sandshrew    Ground       NaN     0.6    12.0          0
28    Sandslash    Ground       NaN     1.0    29.5          0
29     Nidoran♀    Poison       NaN     0.4     7.0          0
30     Nidorina    Poison       NaN     0.8    20.0          0
31    Nidoqueen    Poison    Ground     1.3    60.0          0
32     Nidoran♂    Poison       NaN     0.5     9.0          0
33     Nidorino    Poison       NaN     0.9    19.5          0
34     Nidoking    Poison    Ground     1.4    62.0          0
35     Clefairy     Fairy       NaN     0.6     7.5          0
36     Clefable     Fairy       NaN     1.3    40.0          0
37       Vulpix      Fire       NaN     0.6     9.9          0
38    Ninetales      Fire       NaN     1.1    19.9          0
39   Jigglypuff    Normal     Fairy     0.5     5.5          0
40   Wigglytuff    Normal     Fairy     1.0    12.0          0
41        Zubat    Poison    Flying     0.8     7.5          0
42       Golbat    Poison    Flying     1.6    55.0          0
43       Oddish     Grass    Poison     0.5     5.4          0
44        Gloom     Grass    Poison     0.8     8.6          0
45    Vileplume     Grass    Poison     1.2    18.6          0
46        Paras       Bug     Grass     0.3     5.4          0
47     Parasect       Bug     Grass     1.0    29.5          0
48      Venonat       Bug    Poison     1.0    30.0          0
49     Venomoth       Bug    Poison     1.5    12.5          0
50      Diglett    Ground       NaN     0.2     0.8          0
51      Dugtrio    Ground       NaN     0.7    33.3          0
52       Meowth    Normal       NaN     0.4     4.2          0
53      Persian    Normal       NaN     1.0    32.0          0
54      Psyduck     Water       NaN     0.8    19.6          0
55      Golduck     Water       NaN     1.7    76.6          0
56       Mankey  Fighting       NaN     0.5    28.0          0
57     Primeape  Fighting       NaN     1.0    32.0          0
58    Growlithe      Fire       NaN     0.7    19.0          0
60      Poliwag     Water       NaN     0.6    12.4          0
61    Poliwhirl     Water       NaN     1.0    20.0          0
62    Poliwrath     Water  Fighting     1.3    54.0          0
63         Abra   Psychic       NaN     0.9    19.5          0
64      Kadabra   Psychic       NaN     1.3    56.5          0
65     Alakazam   Psychic       NaN     1.5    48.0          0
66       Machop  Fighting       NaN     0.8    19.5          0
67      Machoke  Fighting       NaN     1.5    70.5          0
69   Bellsprout     Grass    Poison     0.7     4.0          0
70   Weepinbell     Grass    Poison     1.0     6.4          0
71   Victreebel     Grass    Poison     1.7    15.5          0
72    Tentacool     Water    Poison     0.9    45.5          0
73   Tentacruel     Water    Poison     1.6    55.0          0
74      Geodude      Rock    Ground     0.4    20.0          0
77       Ponyta      Fire       NaN     1.0    30.0          0
78     Rapidash      Fire       NaN     1.7    95.0          0
79     Slowpoke     Water   Psychic     1.2    36.0          0
80      Slowbro     Water   Psychic     1.6    78.5          0
81    Magnemite  Electric     Steel     0.3     6.0          0
82     Magneton  Electric     Steel     1.0    60.0          0
83   Farfetch'd    Normal    Flying     0.8    15.0          0
84        Doduo    Normal    Flying     1.4    39.2          0
85       Dodrio    Normal    Flying     1.8    85.2          0
86         Seel     Water       NaN     1.1    90.0          0
88       Grimer    Poison       NaN     0.9    30.0          0
89          Muk    Poison       NaN     1.2    30.0          0
90     Shellder     Water       NaN     0.3     4.0          0
92       Gastly     Ghost    Poison     1.3     0.1          0
93      Haunter     Ghost    Poison     1.6     0.1          0
94       Gengar     Ghost    Poison     1.5    40.5          0
96      Drowzee   Psychic       NaN     1.0    32.4          0
97        Hypno   Psychic       NaN     1.6    75.6          0
98       Krabby     Water       NaN     0.4     6.5          0
99      Kingler     Water       NaN     1.3    60.0          0
100     Voltorb  Electric       NaN     0.5    10.4          0
101   Electrode  Electric       NaN     1.2    66.6          0
102   Exeggcute     Grass   Psychic     0.4     2.5          0
104      Cubone    Ground       NaN     0.4     6.5          0
105     Marowak    Ground       NaN     1.0    45.0          0
106   Hitmonlee  Fighting       NaN     1.5    49.8          0
107  Hitmonchan  Fighting       NaN     1.4    50.2          0
108   Lickitung    Normal       NaN     1.2    65.5          0
109     Koffing    Poison       NaN     0.6     1.0          0
110     Weezing    Poison       NaN     1.2     9.5          0
113     Chansey    Normal       NaN     1.1    34.6          0
114     Tangela     Grass       NaN     1.0    35.0          0
115  Kangaskhan    Normal       NaN     2.2    80.0          0
116      Horsea     Water       NaN     0.4     8.0          0
117      Seadra     Water       NaN     1.2    25.0          0
118     Goldeen     Water       NaN     0.6    15.0          0
119     Seaking     Water       NaN     1.3    39.0          0
120      Staryu     Water       NaN     0.8    34.5          0
121     Starmie     Water   Psychic     1.1    80.0          0
122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
123     Scyther       Bug    Flying     1.5    56.0          0
124        Jynx       Ice   Psychic     1.4    40.6          0
125  Electabuzz  Electric       NaN     1.1    30.0          0
126      Magmar      Fire       NaN     1.3    44.5          0
127      Pinsir       Bug       NaN     1.5    55.0          0
128      Tauros    Normal       NaN     1.4    88.4          0
129    Magikarp     Water       NaN     0.9    10.0          0
132       Ditto    Normal       NaN     0.3     4.0          0
133       Eevee    Normal       NaN     0.3     6.5          0
134    Vaporeon     Water       NaN     1.0    29.0          0
135     Jolteon  Electric       NaN     0.8    24.5          0
136     Flareon      Fire       NaN     0.9    25.0          0
137     Porygon    Normal       NaN     0.8    36.5          0
138     Omanyte      Rock     Water     0.4     7.5          0
139     Omastar      Rock     Water     1.0    35.0          0
140      Kabuto      Rock     Water     0.5    11.5          0
141    Kabutops      Rock     Water     1.3    40.5          0
142  Aerodactyl      Rock    Flying     1.8    59.0          0
144    Articuno       Ice    Flying     1.7    55.4          1
145      Zapdos  Electric    Flying     1.6    52.6          1
146     Moltres      Fire    Flying     2.0    60.0          1
147     Dratini    Dragon       NaN     1.8     3.3          0
148   Dragonair    Dragon       NaN     4.0    16.5          0

In [311]:
print(df["Legendary"].to_string())

No
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    1
145    1
146    1
147    0
148    0
149    0
150    1

In [326]:
print(df[df["Legendary"]==1])

         Name     Type1   Type2  Height  Weight  Legendary
No
144  Articuno       Ice  Flying     1.7    55.4          1
145    Zapdos  Electric  Flying     1.6    52.6          1
146   Moltres      Fire  Flying     2.0    60.0          1
150    Mewtwo   Psychic     NaN     2.0   122.0          1

In [327]:
print(df[df["Legendary"]==True])

         Name     Type1   Type2  Height  Weight  Legendary
No
144  Articuno       Ice  Flying     1.7    55.4          1
145    Zapdos  Electric  Flying     1.6    52.6          1
146   Moltres      Fire  Flying     2.0    60.0          1
150    Mewtwo   Psychic     NaN     2.0   122.0          1

In [346]:
# Exersises of Filtering of Data

In [343]:
# Printing those Pokemons that have powers of  Ice or Flying
print(df[(df["Type1"]=="Ice") | (df["Type2"]=="Flying")])

           Name     Type1    Type2  Height  Weight  Legendary
No
6     Charizard      Fire   Flying     1.7    90.5          0
12   Butterfree       Bug   Flying     1.1    32.0          0
16       Pidgey    Normal   Flying     0.3     1.8          0
17    Pidgeotto    Normal   Flying     1.1    30.0          0
18      Pidgeot    Normal   Flying     1.5    39.5          0
21      Spearow    Normal   Flying     0.3     2.0          0
22       Fearow    Normal   Flying     1.2    38.0          0
41        Zubat    Poison   Flying     0.8     7.5          0
42       Golbat    Poison   Flying     1.6    55.0          0
83   Farfetch'd    Normal   Flying     0.8    15.0          0
84        Doduo    Normal   Flying     1.4    39.2          0
85       Dodrio    Normal   Flying     1.8    85.2          0
123     Scyther       Bug   Flying     1.5    56.0          0
124        Jynx       Ice  Psychic     1.4    40.6          0
130    Gyarados     Water   Flying     6.5   235.0          0
142  Aerodactyl      Rock   Flying     1.8    59.0          0
144    Articuno       Ice   Flying     1.7    55.4          1
145      Zapdos  Electric   Flying     1.6    52.6          1
146     Moltres      Fire   Flying     2.0    60.0          1
149   Dragonite    Dragon   Flying     2.2   210.0          0

In [335]:
# Printing those Pokemons that have powers of Ice as well as Water
print(df[(df["Type1"]=="Ice") & (df["Type2"]=="Flying")])

         Name Type1   Type2  Height  Weight  Legendary
No
144  Articuno   Ice  Flying     1.7    55.4          1

In [342]:
# Printing Water Pokemons
print(df[(df["Type1"]=="Water")|(df["Type2"]=="Water")])

           Name  Type1     Type2  Height  Weight  Legendary
No
7      Squirtle  Water       NaN     0.5     9.0          0
8     Wartortle  Water       NaN     1.0    22.5          0
9     Blastoise  Water       NaN     1.6    85.5          0
54      Psyduck  Water       NaN     0.8    19.6          0
55      Golduck  Water       NaN     1.7    76.6          0
60      Poliwag  Water       NaN     0.6    12.4          0
61    Poliwhirl  Water       NaN     1.0    20.0          0
62    Poliwrath  Water  Fighting     1.3    54.0          0
72    Tentacool  Water    Poison     0.9    45.5          0
73   Tentacruel  Water    Poison     1.6    55.0          0
79     Slowpoke  Water   Psychic     1.2    36.0          0
80      Slowbro  Water   Psychic     1.6    78.5          0
86         Seel  Water       NaN     1.1    90.0          0
87      Dewgong  Water       Ice     1.7   120.0          0
90     Shellder  Water       NaN     0.3     4.0          0
91     Cloyster  Water       Ice     1.5   132.5          0
98       Krabby  Water       NaN     0.4     6.5          0
99      Kingler  Water       NaN     1.3    60.0          0
116      Horsea  Water       NaN     0.4     8.0          0
117      Seadra  Water       NaN     1.2    25.0          0
118     Goldeen  Water       NaN     0.6    15.0          0
119     Seaking  Water       NaN     1.3    39.0          0
120      Staryu  Water       NaN     0.8    34.5          0
121     Starmie  Water   Psychic     1.1    80.0          0
129    Magikarp  Water       NaN     0.9    10.0          0
130    Gyarados  Water    Flying     6.5   235.0          0
131      Lapras  Water       Ice     2.5   220.0          0
134    Vaporeon  Water       NaN     1.0    29.0          0
138     Omanyte   Rock     Water     0.4     7.5          0
139     Omastar   Rock     Water     1.0    35.0          0
140      Kabuto   Rock     Water     0.5    11.5          0
141    Kabutops   Rock     Water     1.3    40.5          0

In [345]:
# Printing Those Pokemons that have Powers of Both Fire as well as Flying
print(df[(df["Type1"]=="Fire")&(df["Type2"]=="Flying")])

          Name Type1   Type2  Height  Weight  Legendary
No
6    Charizard  Fire  Flying     1.7    90.5          0
146    Moltres  Fire  Flying     2.0    60.0          1

# Aggregation:
- Aggregate Funtions=Reduces a set of values into a single Summary Value
- It is used to Summarize and Analyze data

In [348]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="No")
df

           Name    Type1   Type2  Height  Weight  Legendary
No
1     Bulbasaur    Grass  Poison     0.7     6.9          0
2       Ivysaur    Grass  Poison     1.0    13.0          0
3      Venusaur    Grass  Poison     2.0   100.0          0
4    Charmander     Fire     NaN     0.6     8.5          0
5    Charmeleon     Fire     NaN     1.1    19.0          0
..          ...      ...     ...     ...     ...        ...
146     Moltres     Fire  Flying     2.0    60.0          1
147     Dratini   Dragon     NaN     1.8     3.3          0
148   Dragonair   Dragon     NaN     4.0    16.5          0
149   Dragonite   Dragon  Flying     2.2   210.0          0
150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [351]:
 
#print(df.mean())  It will through Errors as this dataset also consist of columns of having text values
print(df.mean(numeric_only=True))

Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64

In [358]:
print("The Mean Values at each Column:")
print(df.mean(numeric_only=True))
print("\n")
print("The Sum Values at each Column:")
print(df.sum(numeric_only=True))
print("\n")
print("The Minimum Values at each Column:")
print(df.min(numeric_only=True))
print("\n")
print("The Maximum Values at each Column:")
print(df.max(numeric_only=True))
print("\n")
print("The Total Count values  of Each  Column:")
print(df.count())
print("\n")

The Mean Values at each Column:
Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64


The Sum Values at each Column:
Height        180.0
Weight       6934.7
Legendary       4.0
dtype: float64


The Minimum Values at each Column:
Height       0.2
Weight       0.1
Legendary    0.0
dtype: float64


The Maximum Values at each Column:
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64


The Total Count values  of Each  Column:
Name         150
Type1        150
Type2         67
Height       150
Weight       150
Legendary    150
dtype: int64

### Now for Specifc Column

In [363]:
print("The Mean Values at each Column:")
print(df["Height"].mean())

print("The Sum Values at each Column:")
print(df["Height"].sum())

print("The Minimum Values at each Column:")
print(df["Height"].min())

print("The Maximum Values at each Column:")
print(df["Height"].max())

print("The Total Count values  of Each  Column:")
print(df["Height"].count())

The Mean Values at each Column:
1.2
The Sum Values at each Column:
180.0
The Minimum Values at each Column:
0.2
The Maximum Values at each Column:
8.8
The Total Count values  of Each  Column:
150

### Using Aggreagate Funtions With groupby()
- Aggreate Funtions are used to Summarize and Analyse Data, often used with  the groupby() Funtion

In [365]:
Group=df.groupby("Type1")
print("The Mean Value of Height Column:")
print(Group["Height"].mean())

print("The Sum Values Height Column:")
print(Group["Height"].sum())

print("The Minimum Values Height Column:")
print(Group["Height"].min())

print("The Maximum Values Height Column:")
print(Group["Height"].max())

print("The Total Count values Height Column:")
print(Group["Height"].count())

The Mean Value of Height Column:
Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64
The Sum Values Height Column:
Type1
Bug         10.8
Dragon       8.0
Electric     7.7
Fairy        1.9
Fighting     8.3
Fire        14.6
Ghost        4.4
Grass       13.0
Ground       6.8
Ice          3.1
Normal      21.7
Poison      17.1
Psychic      9.6
Rock        16.6
Water       36.4
Name: Height, dtype: float64
The Minimum Values Height Column:
Type1
Bug         0.3
Dragon      1.8
Electric    0.3
Fairy       0.6
Fighting    0.5
Fire        0.6
Ghost       1.3
Grass       0.4
Ground      0.2
Ice         1.4
Normal      0.3
Poison      0.4
Psychic     0.9
Rock        0.4
Water       0.3
Name: Height, dtype: float64
The Maximum Values Height Column:
Type1
Bug         1.5
Dragon      4.0
Electric    1.6
Fairy       1.3
Fighting    1.6
Fire        2.0
Ghost       1.6
Grass       2.0
Ground      1.9
Ice         1.7
Normal      2.2
Poison      3.5
Psychic     2.0
Rock        8.8
Water       6.5
Name: Height, dtype: float64
The Total Count values Height Column:
Type1
Bug         12
Dragon       3
Electric     9
Fairy        2
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      22
Poison      14
Psychic      7
Rock         9
Water       28
Name: Height, dtype: int64

# Data Cleaning

##### Data Cleaning =The Process of Fixing/Removing,Incomplete,incorrect or irrelevant data
#####  75% of Work Done With Pandas is data Cleaning

In [407]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Umair\OneDrive\Desktop\data-science-practice\data_analyst_practice\Python\Pandas\data.csv",index_col="No")
df

           Name    Type1   Type2  Height  Weight  Legendary
No
1     Bulbasaur    Grass  Poison     0.7     6.9          0
2       Ivysaur    Grass  Poison     1.0    13.0          0
3      Venusaur    Grass  Poison     2.0   100.0          0
4    Charmander     Fire     NaN     0.6     8.5          0
5    Charmeleon     Fire     NaN     1.1    19.0          0
..          ...      ...     ...     ...     ...        ...
146     Moltres     Fire  Flying     2.0    60.0          1
147     Dratini   Dragon     NaN     1.8     3.3          0
148   Dragonair   Dragon     NaN     4.0    16.5          0
149   Dragonite   Dragon  Flying     2.2   210.0          0
150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [405]:
### Steps :
Drop Irrelevant Columns
Handle Missing Data
Fix Inconsistent Values
Standardize text
Fix Data types
Remove Duplicate Values

In [383]:
# Drop Irrelevant Columns:
df=df.drop(columns=["Legendary"])
df

           Name    Type1   Type2  Height  Weight
No
1     Bulbasaur    Grass  Poison     0.7     6.9
2       Ivysaur    Grass  Poison     1.0    13.0
3      Venusaur    Grass  Poison     2.0   100.0
4    Charmander     Fire     NaN     0.6     8.5
5    Charmeleon     Fire     NaN     1.1    19.0
..          ...      ...     ...     ...     ...
146     Moltres     Fire  Flying     2.0    60.0
147     Dratini   Dragon     NaN     1.8     3.3
148   Dragonair   Dragon     NaN     4.0    16.5
149   Dragonite   Dragon  Flying     2.2   210.0
150      Mewtwo  Psychic     NaN     2.0   122.0

[150 rows x 5 columns]

In [384]:
# Drop Multiple Irrelevant Columns:
df=df.drop(columns=["Height","Weight"])
df

           Name    Type1   Type2
No
1     Bulbasaur    Grass  Poison
2       Ivysaur    Grass  Poison
3      Venusaur    Grass  Poison
4    Charmander     Fire     NaN
5    Charmeleon     Fire     NaN
..          ...      ...     ...
146     Moltres     Fire  Flying
147     Dratini   Dragon     NaN
148   Dragonair   Dragon     NaN
149   Dragonite   Dragon  Flying
150      Mewtwo  Psychic     NaN

[150 rows x 3 columns]

In [391]:
#2. Handle Missing data(i.e NAN)
df=df.dropna(subset=["Type1","Type2"])
print(df.to_string())

           Name     Type1     Type2
No
1     Bulbasaur     Grass    Poison
2       Ivysaur     Grass    Poison
3      Venusaur     Grass    Poison
6     Charizard      Fire    Flying
12   Butterfree       Bug    Flying
13       Weedle       Bug    Poison
14       Kakuna       Bug    Poison
15     Beedrill       Bug    Poison
16       Pidgey    Normal    Flying
17    Pidgeotto    Normal    Flying
18      Pidgeot    Normal    Flying
21      Spearow    Normal    Flying
22       Fearow    Normal    Flying
31    Nidoqueen    Poison    Ground
34     Nidoking    Poison    Ground
39   Jigglypuff    Normal     Fairy
40   Wigglytuff    Normal     Fairy
41        Zubat    Poison    Flying
42       Golbat    Poison    Flying
43       Oddish     Grass    Poison
44        Gloom     Grass    Poison
45    Vileplume     Grass    Poison
46        Paras       Bug     Grass
47     Parasect       Bug     Grass
48      Venonat       Bug    Poison
49     Venomoth       Bug    Poison
62    Poliwrath     Water  Fighting
69   Bellsprout     Grass    Poison
70   Weepinbell     Grass    Poison
71   Victreebel     Grass    Poison
72    Tentacool     Water    Poison
73   Tentacruel     Water    Poison
74      Geodude      Rock    Ground
75     Graveler      Rock    Ground
76        Golem      Rock    Ground
79     Slowpoke     Water   Psychic
80      Slowbro     Water   Psychic
81    Magnemite  Electric     Steel
82     Magneton  Electric     Steel
83   Farfetch'd    Normal    Flying
84        Doduo    Normal    Flying
85       Dodrio    Normal    Flying
87      Dewgong     Water       Ice
91     Cloyster     Water       Ice
92       Gastly     Ghost    Poison
93      Haunter     Ghost    Poison
94       Gengar     Ghost    Poison
95         Onix      Rock    Ground
102   Exeggcute     Grass   Psychic
103   Exeggutor     Grass   Psychic
111     Rhyhorn    Ground      Rock
112      Rhydon    Ground      Rock
121     Starmie     Water   Psychic
122    Mr. Mime   Psychic     Fairy
123     Scyther       Bug    Flying
124        Jynx       Ice   Psychic
130    Gyarados     Water    Flying
131      Lapras     Water       Ice
138     Omanyte      Rock     Water
139     Omastar      Rock     Water
140      Kabuto      Rock     Water
141    Kabutops      Rock     Water
142  Aerodactyl      Rock    Flying
144    Articuno       Ice    Flying
145      Zapdos  Electric    Flying
146     Moltres      Fire    Flying
149   Dragonite    Dragon    Flying

In [397]:
# 3. Fix Incosistent values 
df["Type1"]=df["Type1"].replace({"Water":"WATER","Grass":"GRASS"})
print(df.to_string())

           Name     Type1     Type2
No
1     Bulbasaur     GRASS    Poison
2       Ivysaur     GRASS    Poison
3      Venusaur     GRASS    Poison
6     Charizard      Fire    Flying
12   Butterfree       Bug    Flying
13       Weedle       Bug    Poison
14       Kakuna       Bug    Poison
15     Beedrill       Bug    Poison
16       Pidgey    Normal    Flying
17    Pidgeotto    Normal    Flying
18      Pidgeot    Normal    Flying
21      Spearow    Normal    Flying
22       Fearow    Normal    Flying
31    Nidoqueen    Poison    Ground
34     Nidoking    Poison    Ground
39   Jigglypuff    Normal     Fairy
40   Wigglytuff    Normal     Fairy
41        Zubat    Poison    Flying
42       Golbat    Poison    Flying
43       Oddish     GRASS    Poison
44        Gloom     GRASS    Poison
45    Vileplume     GRASS    Poison
46        Paras       Bug     Grass
47     Parasect       Bug     Grass
48      Venonat       Bug    Poison
49     Venomoth       Bug    Poison
62    Poliwrath     WATER  Fighting
69   Bellsprout     GRASS    Poison
70   Weepinbell     GRASS    Poison
71   Victreebel     GRASS    Poison
72    Tentacool     WATER    Poison
73   Tentacruel     WATER    Poison
74      Geodude      Rock    Ground
75     Graveler      Rock    Ground
76        Golem      Rock    Ground
79     Slowpoke     WATER   Psychic
80      Slowbro     WATER   Psychic
81    Magnemite  Electric     Steel
82     Magneton  Electric     Steel
83   Farfetch'd    Normal    Flying
84        Doduo    Normal    Flying
85       Dodrio    Normal    Flying
87      Dewgong     WATER       Ice
91     Cloyster     WATER       Ice
92       Gastly     Ghost    Poison
93      Haunter     Ghost    Poison
94       Gengar     Ghost    Poison
95         Onix      Rock    Ground
102   Exeggcute     GRASS   Psychic
103   Exeggutor     GRASS   Psychic
111     Rhyhorn    Ground      Rock
112      Rhydon    Ground      Rock
121     Starmie     WATER   Psychic
122    Mr. Mime   Psychic     Fairy
123     Scyther       Bug    Flying
124        Jynx       Ice   Psychic
130    Gyarados     WATER    Flying
131      Lapras     WATER       Ice
138     Omanyte      Rock     Water
139     Omastar      Rock     Water
140      Kabuto      Rock     Water
141    Kabutops      Rock     Water
142  Aerodactyl      Rock    Flying
144    Articuno       Ice    Flying
145      Zapdos  Electric    Flying
146     Moltres      Fire    Flying
149   Dragonite    Dragon    Flying

In [402]:
# 4. Standardize Text :
df["Name"]=df["Name"].str.lower()
df["Type1"]=df["Type1"].str.lower()
df["Type2"]=df["Type2"].str.lower()


print(df.to_string())

           Name     Type1     Type2
No
1     bulbasaur     grass    poison
2       ivysaur     grass    poison
3      venusaur     grass    poison
6     charizard      fire    flying
12   butterfree       bug    flying
13       weedle       bug    poison
14       kakuna       bug    poison
15     beedrill       bug    poison
16       pidgey    normal    flying
17    pidgeotto    normal    flying
18      pidgeot    normal    flying
21      spearow    normal    flying
22       fearow    normal    flying
31    nidoqueen    poison    ground
34     nidoking    poison    ground
39   jigglypuff    normal     fairy
40   wigglytuff    normal     fairy
41        zubat    poison    flying
42       golbat    poison    flying
43       oddish     grass    poison
44        gloom     grass    poison
45    vileplume     grass    poison
46        paras       bug     grass
47     parasect       bug     grass
48      venonat       bug    poison
49     venomoth       bug    poison
62    poliwrath     water  fighting
69   bellsprout     grass    poison
70   weepinbell     grass    poison
71   victreebel     grass    poison
72    tentacool     water    poison
73   tentacruel     water    poison
74      geodude      rock    ground
75     graveler      rock    ground
76        golem      rock    ground
79     slowpoke     water   psychic
80      slowbro     water   psychic
81    magnemite  electric     steel
82     magneton  electric     steel
83   farfetch'd    normal    flying
84        doduo    normal    flying
85       dodrio    normal    flying
87      dewgong     water       ice
91     cloyster     water       ice
92       gastly     ghost    poison
93      haunter     ghost    poison
94       gengar     ghost    poison
95         onix      rock    ground
102   exeggcute     grass   psychic
103   exeggutor     grass   psychic
111     rhyhorn    ground      rock
112      rhydon    ground      rock
121     starmie     water   psychic
122    mr. mime   psychic     fairy
123     scyther       bug    flying
124        jynx       ice   psychic
130    gyarados     water    flying
131      lapras     water       ice
138     omanyte      rock     water
139     omastar      rock     water
140      kabuto      rock     water
141    kabutops      rock     water
142  aerodactyl      rock    flying
144    articuno       ice    flying
145      zapdos  electric    flying
146     moltres      fire    flying
149   dragonite    dragon    flying

In [408]:
# 5. Fix Data Types
df["Legendary"]=df["Legendary"].astype(bool)
print(df.to_string())

           Name     Type1     Type2  Height  Weight  Legendary
No
1     Bulbasaur     Grass    Poison     0.7     6.9      False
2       Ivysaur     Grass    Poison     1.0    13.0      False
3      Venusaur     Grass    Poison     2.0   100.0      False
4    Charmander      Fire       NaN     0.6     8.5      False
5    Charmeleon      Fire       NaN     1.1    19.0      False
6     Charizard      Fire    Flying     1.7    90.5      False
7      Squirtle     Water       NaN     0.5     9.0      False
8     Wartortle     Water       NaN     1.0    22.5      False
9     Blastoise     Water       NaN     1.6    85.5      False
10     Caterpie       Bug       NaN     0.3     2.9      False
11      Metapod       Bug       NaN     0.7     9.9      False
12   Butterfree       Bug    Flying     1.1    32.0      False
13       Weedle       Bug    Poison     0.3     3.2      False
14       Kakuna       Bug    Poison     0.6    10.0      False
15     Beedrill       Bug    Poison     1.0    29.5      False
16       Pidgey    Normal    Flying     0.3     1.8      False
17    Pidgeotto    Normal    Flying     1.1    30.0      False
18      Pidgeot    Normal    Flying     1.5    39.5      False
19      Rattata    Normal       NaN     0.3     3.5      False
20     Raticate    Normal       NaN     0.7    18.5      False
21      Spearow    Normal    Flying     0.3     2.0      False
22       Fearow    Normal    Flying     1.2    38.0      False
23        Ekans    Poison       NaN     2.0     6.9      False
24        Arbok    Poison       NaN     3.5    65.0      False
25      Pikachu  Electric       NaN     0.4     6.0      False
26       Raichu  Electric       NaN     0.8    30.0      False
27    Sandshrew    Ground       NaN     0.6    12.0      False
28    Sandslash    Ground       NaN     1.0    29.5      False
29     Nidoran♀    Poison       NaN     0.4     7.0      False
30     Nidorina    Poison       NaN     0.8    20.0      False
31    Nidoqueen    Poison    Ground     1.3    60.0      False
32     Nidoran♂    Poison       NaN     0.5     9.0      False
33     Nidorino    Poison       NaN     0.9    19.5      False
34     Nidoking    Poison    Ground     1.4    62.0      False
35     Clefairy     Fairy       NaN     0.6     7.5      False
36     Clefable     Fairy       NaN     1.3    40.0      False
37       Vulpix      Fire       NaN     0.6     9.9      False
38    Ninetales      Fire       NaN     1.1    19.9      False
39   Jigglypuff    Normal     Fairy     0.5     5.5      False
40   Wigglytuff    Normal     Fairy     1.0    12.0      False
41        Zubat    Poison    Flying     0.8     7.5      False
42       Golbat    Poison    Flying     1.6    55.0      False
43       Oddish     Grass    Poison     0.5     5.4      False
44        Gloom     Grass    Poison     0.8     8.6      False
45    Vileplume     Grass    Poison     1.2    18.6      False
46        Paras       Bug     Grass     0.3     5.4      False
47     Parasect       Bug     Grass     1.0    29.5      False
48      Venonat       Bug    Poison     1.0    30.0      False
49     Venomoth       Bug    Poison     1.5    12.5      False
50      Diglett    Ground       NaN     0.2     0.8      False
51      Dugtrio    Ground       NaN     0.7    33.3      False
52       Meowth    Normal       NaN     0.4     4.2      False
53      Persian    Normal       NaN     1.0    32.0      False
54      Psyduck     Water       NaN     0.8    19.6      False
55      Golduck     Water       NaN     1.7    76.6      False
56       Mankey  Fighting       NaN     0.5    28.0      False
57     Primeape  Fighting       NaN     1.0    32.0      False
58    Growlithe      Fire       NaN     0.7    19.0      False
59     Arcanine      Fire       NaN     1.9   155.0      False
60      Poliwag     Water       NaN     0.6    12.4      False
61    Poliwhirl     Water       NaN     1.0    20.0      False
62    Poliwrath     Water  Fighting     1.3    54.0      False
63         Abra   Psychic       NaN     0.9    19.5      False
64      Kadabra   Psychic       NaN     1.3    56.5      False
65     Alakazam   Psychic       NaN     1.5    48.0      False
66       Machop  Fighting       NaN     0.8    19.5      False
67      Machoke  Fighting       NaN     1.5    70.5      False
68      Machamp  Fighting       NaN     1.6   130.0      False
69   Bellsprout     Grass    Poison     0.7     4.0      False
70   Weepinbell     Grass    Poison     1.0     6.4      False
71   Victreebel     Grass    Poison     1.7    15.5      False
72    Tentacool     Water    Poison     0.9    45.5      False
73   Tentacruel     Water    Poison     1.6    55.0      False
74      Geodude      Rock    Ground     0.4    20.0      False
75     Graveler      Rock    Ground     1.0   105.0      False
76        Golem      Rock    Ground     1.4   300.0      False
77       Ponyta      Fire       NaN     1.0    30.0      False
78     Rapidash      Fire       NaN     1.7    95.0      False
79     Slowpoke     Water   Psychic     1.2    36.0      False
80      Slowbro     Water   Psychic     1.6    78.5      False
81    Magnemite  Electric     Steel     0.3     6.0      False
82     Magneton  Electric     Steel     1.0    60.0      False
83   Farfetch'd    Normal    Flying     0.8    15.0      False
84        Doduo    Normal    Flying     1.4    39.2      False
85       Dodrio    Normal    Flying     1.8    85.2      False
86         Seel     Water       NaN     1.1    90.0      False
87      Dewgong     Water       Ice     1.7   120.0      False
88       Grimer    Poison       NaN     0.9    30.0      False
89          Muk    Poison       NaN     1.2    30.0      False
90     Shellder     Water       NaN     0.3     4.0      False
91     Cloyster     Water       Ice     1.5   132.5      False
92       Gastly     Ghost    Poison     1.3     0.1      False
93      Haunter     Ghost    Poison     1.6     0.1      False
94       Gengar     Ghost    Poison     1.5    40.5      False
95         Onix      Rock    Ground     8.8   210.0      False
96      Drowzee   Psychic       NaN     1.0    32.4      False
97        Hypno   Psychic       NaN     1.6    75.6      False
98       Krabby     Water       NaN     0.4     6.5      False
99      Kingler     Water       NaN     1.3    60.0      False
100     Voltorb  Electric       NaN     0.5    10.4      False
101   Electrode  Electric       NaN     1.2    66.6      False
102   Exeggcute     Grass   Psychic     0.4     2.5      False
103   Exeggutor     Grass   Psychic     2.0   120.0      False
104      Cubone    Ground       NaN     0.4     6.5      False
105     Marowak    Ground       NaN     1.0    45.0      False
106   Hitmonlee  Fighting       NaN     1.5    49.8      False
107  Hitmonchan  Fighting       NaN     1.4    50.2      False
108   Lickitung    Normal       NaN     1.2    65.5      False
109     Koffing    Poison       NaN     0.6     1.0      False
110     Weezing    Poison       NaN     1.2     9.5      False
111     Rhyhorn    Ground      Rock     1.0   115.0      False
112      Rhydon    Ground      Rock     1.9   120.0      False
113     Chansey    Normal       NaN     1.1    34.6      False
114     Tangela     Grass       NaN     1.0    35.0      False
115  Kangaskhan    Normal       NaN     2.2    80.0      False
116      Horsea     Water       NaN     0.4     8.0      False
117      Seadra     Water       NaN     1.2    25.0      False
118     Goldeen     Water       NaN     0.6    15.0      False
119     Seaking     Water       NaN     1.3    39.0      False
120      Staryu     Water       NaN     0.8    34.5      False
121     Starmie     Water   Psychic     1.1    80.0      False
122    Mr. Mime   Psychic     Fairy     1.3    54.5      False
123     Scyther       Bug    Flying     1.5    56.0      False
124        Jynx       Ice   Psychic     1.4    40.6      False
125  Electabuzz  Electric       NaN     1.1    30.0      False
126      Magmar      Fire       NaN     1.3    44.5      False
127      Pinsir       Bug       NaN     1.5    55.0      False
128      Tauros    Normal       NaN     1.4    88.4      False
129    Magikarp     Water       NaN     0.9    10.0      False
130    Gyarados     Water    Flying     6.5   235.0      False
131      Lapras     Water       Ice     2.5   220.0      False
132       Ditto    Normal       NaN     0.3     4.0      False
133       Eevee    Normal       NaN     0.3     6.5      False
134    Vaporeon     Water       NaN     1.0    29.0      False
135     Jolteon  Electric       NaN     0.8    24.5      False
136     Flareon      Fire       NaN     0.9    25.0      False
137     Porygon    Normal       NaN     0.8    36.5      False
138     Omanyte      Rock     Water     0.4     7.5      False
139     Omastar      Rock     Water     1.0    35.0      False
140      Kabuto      Rock     Water     0.5    11.5      False
141    Kabutops      Rock     Water     1.3    40.5      False
142  Aerodactyl      Rock    Flying     1.8    59.0      False
143     Snorlax    Normal       NaN     2.1   460.0      False
144    Articuno       Ice    Flying     1.7    55.4       True
145      Zapdos  Electric    Flying     1.6    52.6       True
146     Moltres      Fire    Flying     2.0    60.0       True
147     Dratini    Dragon       NaN     1.8     3.3      False
148   Dragonair    Dragon       NaN     4.0    16.5      False
149   Dragonite    Dragon    Flying     2.2   210.0      False
150      Mewtwo   Psychic       NaN     2.0   122.0       True

In [404]:
# 6. Remove Duplicate Values:
df=df.drop_duplicates()
print(df.to_string())

           Name     Type1     Type2
No
1     bulbasaur     grass    poison
2       ivysaur     grass    poison
3      venusaur     grass    poison
6     charizard      fire    flying
12   butterfree       bug    flying
13       weedle       bug    poison
14       kakuna       bug    poison
15     beedrill       bug    poison
16       pidgey    normal    flying
17    pidgeotto    normal    flying
18      pidgeot    normal    flying
21      spearow    normal    flying
22       fearow    normal    flying
31    nidoqueen    poison    ground
34     nidoking    poison    ground
39   jigglypuff    normal     fairy
40   wigglytuff    normal     fairy
41        zubat    poison    flying
42       golbat    poison    flying
43       oddish     grass    poison
44        gloom     grass    poison
45    vileplume     grass    poison
46        paras       bug     grass
47     parasect       bug     grass
48      venonat       bug    poison
49     venomoth       bug    poison
62    poliwrath     water  fighting
69   bellsprout     grass    poison
70   weepinbell     grass    poison
71   victreebel     grass    poison
72    tentacool     water    poison
73   tentacruel     water    poison
74      geodude      rock    ground
75     graveler      rock    ground
76        golem      rock    ground
79     slowpoke     water   psychic
80      slowbro     water   psychic
81    magnemite  electric     steel
82     magneton  electric     steel
83   farfetch'd    normal    flying
84        doduo    normal    flying
85       dodrio    normal    flying
87      dewgong     water       ice
91     cloyster     water       ice
92       gastly     ghost    poison
93      haunter     ghost    poison
94       gengar     ghost    poison
95         onix      rock    ground
102   exeggcute     grass   psychic
103   exeggutor     grass   psychic
111     rhyhorn    ground      rock
112      rhydon    ground      rock
121     starmie     water   psychic
122    mr. mime   psychic     fairy
123     scyther       bug    flying
124        jynx       ice   psychic
130    gyarados     water    flying
131      lapras     water       ice
138     omanyte      rock     water
139     omastar      rock     water
140      kabuto      rock     water
141    kabutops      rock     water
142  aerodactyl      rock    flying
144    articuno       ice    flying
145      zapdos  electric    flying
146     moltres      fire    flying
149   dragonite    dragon    flying

### ---------------Complete Pandas Basic Notes Practice------------------------